export const ActionTypes = {
  GET_PROTOCOL_OVERVIEW: "GET_PROTOCOL_OVERVIEW",
  GET_PROTOCOL_VIEW: "GET_PROTOCOL_VIEW",
  GET_RELATED_PROTOCOL: "GET_RELATED_PROTOCOL",
  GET_PROTOCOL_VIEW_NEW: "GET_PROTOCOL_VIEW_NEW",
  GET_FILE_STREAM: "GET_FILE_STREAM",
};
