image: node:12.20

cache:
  paths:
    - node_modules/

stages:
  - test
  - build_and_deploy

test:
  stage: test

  tags: 
    - pd-ui-dev
  script:
    - echo "Testing App"
    - npm install
    - npm run test
    - echo "Test successfully!"
  allow_failure: true
  only:
    refs:
      - Sonar-CICD
    variables: 
      - $ENVIRONMENT== "dev"

build:
  stage: build_and_deploy

  tags: 
    - pd-ui-dev

  script: 
    - echo "Start building App"
    - sh CI-scripts/deploy.sh
    - echo "Build and Deployed Successfully!"

  artifacts:
    paths:
      - build
      
  only:
    refs:
      - Sonar-CICD
    variables: 
      - $ENVIRONMENT== "dev"
