#image: node:12.18.4

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/
    - .yarn

before_script:
  # Install yarn as outlined in (https://yarnpkg.com/lang/en/docs/install/#alternatives-stable)
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  # Make available in the current terminal
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
  - yarn install --cache-folder .yarn

build:
  image: node:12.20.1
  stage: build
  tags:
    - 06d-ui-runner
  script:
    - yarn --version
    - rm -rf build
    - CI=false yarn install
    - CI=false yarn build
  artifacts:
    paths:
      - ./build
  only:
    - master

.test:
  stage: test
  script:
    - CI=true yarn test
  only:
    - master



.deploy_dev:
  stage: deploy
  script:
    - pm2 restart server.js


  