variables:
  PACKAGE: "pd-ui-git"

image: node:16.14

cache:
  paths:
    - node_modules/

stages:
  - lint-check
  - unit-test-coverage
  - sonar-scan
  - dev-deploy
  - test-deploy
  - uat1-deploy
  - svt-deploy
  - uat-deploy
  - prod-deploy

lint-check:
  stage: lint-check
  script:
    - npm run pd:deps
    - npm run lint 
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/
  allow_failure: true
  only:
    refs:
      - merge_requests
      - /^develop*/
    variables: 
      - $ENVIRONMENT== "dev"
      - $ENVIRONMENT== "test"

unit-test-coverage:
  stage: unit-test-coverage
  script:
    - npm run test:ci 
  
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    paths:
      - coverage/
    when: always
    reports:
      junit:
        - junit.xml
  allow_failure: true
  only:
    refs:
      - merge_requests
      - /^develop*/
      
    variables: 
      - $ENVIRONMENT== "dev"
      - $ENVIRONMENT== "test"

Perform Sonarqube Analysis and quality gate:
  image: sonarsource/sonar-scanner-cli
  stage: sonar-scan
  before_script:
    - echo "Setting up for Sonarqube Analysis on PD $CI_COMMIT_REF_NAME branch"
    - apk upgrade --update-cache --available && apk add openssl
    - openssl s_client -connect   sonarqube.quintiles.com:443 | keytool -import -noprompt -alias sonarqbue_test -keystore $JAVA_HOME/lib/security/cacerts -storepass changeit

  script:
    - echo "Running Sonarqube Analysis on $CI_COMMIT_REF_NAME branch"
    - apk upgrade --update-cache --available && apk add openssl
    - sh CI-scripts/sonarqube.sh branch > /tmp/sonar.log
    - cat /tmp/sonar.log
    - echo "Running Sonarqube quality gate on $CI_COMMIT_REF_NAME branch"
    - sh CI-scripts/qualitygate.sh
  allow_failure: true
  tags:
    - ca2ugitla006p-D4
  only:
    refs:
      - merge_requests
      - /^develop*/
    variables: 
      - $ENVIRONMENT== "dev"
      - $ENVIRONMENT== "test"

dev-deploy:
  stage: dev-deploy

  tags: 
    - pd-ui-dev

  variables:
    GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"

  script: 
    - echo "Start building App"
    - sh CI-scripts/deploy.sh
    - echo "Build and Deployed Successfully!"

  artifacts:
    paths:
      - build
      
  only:
    refs:
      - development
    variables: 
      - $ENVIRONMENT== "dev"

      
test-deploy:
  stage: test-deploy

  tags: 
    - pd-ui-test

  variables:
    GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"

  script: 
    - echo "Start building App"
    - sh CI-scripts/deploy.sh
    - echo "Build and Deployed Successfully!"

  artifacts:
    paths:
      - build
      
  only:
    refs:
      - develop
    variables: 
      - $ENVIRONMENT== "test"


uat1-deploy:
  stage: uat1-deploy

  tags: 
    - pd-ui-uat1

  variables:
    GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"

  script: 
    - echo "Start building App"
    - sh CI-scripts/deploy.sh
    - echo "Build and Deployed Successfully!"

  artifacts:
    paths:
      - build
      
  only:
    refs:
      - develop
      - merge_requests
      - /^release*/
    variables: 
      - $ENVIRONMENT== "uat1"


svt-deploy:
  stage: svt-deploy

  tags: 
    - pd-ui-svt

  variables:
    GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"

  script: 
    - echo "Start building App"
    - sh CI-scripts/deploy.sh
    - echo "Build and Deployed Successfully!"

  artifacts:
    paths:
      - build
      
  only:
    refs:
      - develop
      - merge_requests
      - /^release*/
    variables: 
      - $ENVIRONMENT== "svt"


uat-deploy:
  stage: uat-deploy

  tags: 
    - pd-ui-uat

  variables:
    GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"

  script: 
    - echo "Start building App"
    - sh CI-scripts/deploy.sh
    - echo "Build and Deployed Successfully!"

  artifacts:
    paths:
      - build
      
  only:
    refs:
      - develop
      - merge_requests
      - /^release*/
    variables: 
      - $ENVIRONMENT== "uat"


prod-deploy:
  stage: prod-deploy

  tags: 
    - pd-ui-prod

  variables:
    GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"

  script: 
    - echo "Start building App"
    - sh CI-scripts/deploy.sh
    - echo "Build and Deployed Successfully!"

  artifacts:
    paths:
      - build
      
  only:
    refs:
      - /^release*/
    variables: 
      - $ENVIRONMENT== "prod"

