variables:
  PACKAGE: "pd-ui-git"

image: node:12.20

cache:
  paths:
    - node_modules/

stages:
  - test
  - sonar-scan
  - dev-deploy
  - test-deploy
  - uat1-deploy
  - svt-deploy
  - uat-deploy
  - prod-deploy

test:
  stage: test

  tags: 
    - pd-ui-dev
  script:
    - echo "Testing App"
    - sh CI-scripts/unit-test.sh
    - echo "Test successfully!"
  allow_failure: true
  only:
    refs:
      - develop
    variables: 
      - $ENVIRONMENT== "dev"

Perform Sonarqube Analysis and quality gate:
  image: sonarsource/sonar-scanner-cli
  stage: sonar-scan
  before_script:
    - echo "Setting up for Sonarqube Analysis on PD $CI_COMMIT_REF_NAME branch"
    - apk upgrade --update-cache --available && apk add openssl
    - openssl s_client -connect   usadc-vspsq01.quintiles.net:443 | keytool -import -noprompt -alias sonarqbue_test -keystore $JAVA_HOME/lib/security/cacerts -storepass changeit

  script:
    - echo "Running Sonarqube Analysis on $CI_COMMIT_REF_NAME branch"
    - apk upgrade --update-cache --available && apk add openssl
    - sh CI-scripts/sonarqube.sh branch > /tmp/sonar.log
    - cat /tmp/sonar.log
    - echo "Running Sonarqube quality gate on $CI_COMMIT_REF_NAME branch"
    - sh CI-scripts/qualitygate.sh
  allow_failure: true
  tags:
    - ca2ugitla006p-D4
  only:
    refs:
      - develop
    variables:
      - $ENVIRONMENT== "dev"

dev-deploy:
  stage: dev-deploy

  tags: 
    - pd-ui-dev

  script: 
    - echo "Start building App"
    - sh CI-scripts/deploy.sh
    - echo "Build and Deployed Successfully!"

  artifacts:
    paths:
      - build
      
  only:
    refs:
      - develop
    variables: 
      - $ENVIRONMENT== "dev"

      
test-deploy:
  stage: test-deploy

  tags: 
    - pd-ui-test

  variables:
    GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"

  script: 
    - echo "Start building App"
    - sh CI-scripts/deploy.sh
    - echo "Build and Deployed Successfully!"

  artifacts:
    paths:
      - build
      
  only:
    refs:
      - develop
    variables: 
      - $ENVIRONMENT== "test"


uat1-deploy:
  stage: uat1-deploy

  tags: 
    - pd-ui-uat1

  variables:
    GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"

  script: 
    - echo "Start building App"
    - sh CI-scripts/deploy.sh
    - echo "Build and Deployed Successfully!"

  artifacts:
    paths:
      - build
      
  only:
    refs:
      - release-1.4
    variables: 
      - $ENVIRONMENT== "uat1"


svt-deploy:
  stage: svt-deploy

  tags: 
    - pd-ui-svt

  variables:
    GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"

  script: 
    - echo "Start building App"
    - sh CI-scripts/deploy.sh
    - echo "Build and Deployed Successfully!"

  artifacts:
    paths:
      - build
      
  only:
    refs:
      - release-1.4
    variables: 
      - $ENVIRONMENT== "svt"


uat-deploy:
  stage: uat-deploy

  tags: 
    - pd-ui-uat

  variables:
    GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"

  script: 
    - echo "Start building App"
    - sh CI-scripts/deploy.sh
    - echo "Build and Deployed Successfully!"

  artifacts:
    paths:
      - build
      
  only:
    refs:
      - release-1.4
    variables: 
      - $ENVIRONMENT== "uat"


prod-deploy:
  stage: prod-deploy

  tags: 
    - pd-ui-prod

  variables:
    GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"

  script: 
    - echo "Start building App"
    - sh CI-scripts/deploy.sh
    - echo "Build and Deployed Successfully!"

  artifacts:
    paths:
      - build
      
  only:
    refs:
      - release-1.4
    variables: 
      - $ENVIRONMENT== "prod"

