image: node:12.20.1

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

build:
  #image: node:12.20.1
  stage: build
  tags:
    - 06d-ui-runner
  script:
    - npm install
    - $env:CI=$false; npm run build
  artifacts:
    paths:
      - ./build
  only:
    - master

.test:
  stage: test
  script:
    - npm test
  only:
    - master

.deploy_dev:
  stage: deploy
  script:
    - pm2 restart server.js


  