image: node:12.20

pages:
  cache:
    paths:
    - node_modules/

  stages:
    - test
    - build_and_deploy

  .test:
    stage: test

    tags: 
      - pd-ui-dev
    script:
      - echo "Testing App"
      - npm install
      - npm run test
      - echo "Test successfully!"
    only:
      refs:
        - Redaction
      variables: 
        - $ENVIRONMENT== "dev"

  build:
    stage: build_and_deploy

    tags: 
      - pd-ui-dev

    before_script:
      - Copy-Item "env_backup.txt" -Destination ".env"
    script: 
      - echo "Start building App"
      - npm install
      - npm run build
      - npm install --global pm2@latest
      - npm run stop
      - npm run deploy
      - echo "Build and Deloyed Successfully!"

    artifacts:
      paths:
        - ./build
        
    only:
      refs:
        - Redaction
      variables: 
        - $ENVIRONMENT== "dev"
