image: node:12.20

stages:
  - test
  - build_and_deploy

cache:
  paths:
    - node_modules/

test:
  stage: test

  tags: 
    - pd-ui-test
  script:
    - echo "Testing App"
    - npm install
    - npm test
    - echo "Test successfully!"
  only:
    refs:
      - CICD-develop
    variables: 
      - $ENVIRONMENT== "dev"

build:
  stage: build_and_deploy

  tags: 
    - pd-ui-test

  before_script:
    - Copy-Item "env_backup.txt" -Destination ".env"
  script: 
    - echo "Start building App"
    - npm install
    - npm run build
    - npm install --global pm2@latest
    - npm run stop
    - npm run deploy
    - echo "Build and Deloyed Successfully!"

  artifacts:
    paths:
      - ./build
      
  only:
    refs:
      - CICD-develop
    variables: 
      - $ENVIRONMENT== "dev"
