#image: node:12.18.4

stages:
  - build
  - test
  - deploy

before_script:
  - npm install

cache:
  paths:
    - node_modules/

build:
  image: node:12.20.1
  stage: build
  tags:
    - 06d-ui-runner
  script:
    - CI=false npm build
  artifacts:
    paths:
      - ./build
  only:
    - master

.test:
  stage: test
  script:
    - CI=true yarn test
  only:
    - master



.deploy_dev:
  stage: deploy
  script:
    - pm2 restart server.js


  