const associateData = [
  {
    id: "66350a76-ea36-4082-88ed-b9c9611786a1",
    userId: "1071710",
    fileName: "Protocol-2020-03-09-DOD-1.0-000001.pdf",
    documentFilePath:
      "\\\\quintiles.net\\enterprise\\Services\\protdigtest\\pilot_iqvxml\\66350a76-ea36-4082-88ed-b9c9611786a1\\Protocol-2020-03-09-DOD-1.0-000001.pdf",
    protocol: "Protocol-A2",
    projectId: "",
    sponsor: "3-D Pharmaceuticals",
    indication: "ABCC6 deficiency",
    moleculeDevice: "M",
    amendment: "Y",
    isProcessing: false,
    percentComplete: "100",
    compareStatus: null,
    iqvXmlPathProc: null,
    iqvXmlPathComp: null,
    shortTitle: "",
    versionNumber: "1.3",
    documentStatus: "draft",
    draftVersion: "1.31",
    errorCode: null,
    errorReason: null,
    status: "PROCESS_COMPLETED",
    phase: "I",
    digitizedConfidenceInterval: null,
    completenessOfDigitization: null,
    protocolTitle:
      "A Phase I, Open-label Study to Assess the Safety, Tolerability, Pharmacokinetics and Anti-Tumour Activity of Adavosertib (AZD1775) in Japanese Patients with Advanced Solid Tumours",
    studyStatus: null,
    sourceSystem: null,
    environment: null,
    uploadDate: "2021-02-18T09:29:27.010000",
    timeCreated: "2021-02-18T09:29:27.010000",
    lastUpdated: "2021-02-18T09:43:46.480000",
    userCreated: null,
    userUpdated: null,
    approvalDate: "2020-03-09T00:00:00",
    isActive: true,
    nctId: null,
  },
];
const associateData1 = [
  {
    id: "66350a76-ea36-4082-88ed-b9c9611786a1",
    userId: "1071710",
    fileName: "Protocol-2020-03-09-DOD-1.0-000001.pdf",
    documentFilePath:
      "\\\\quintiles.net\\enterprise\\Services\\protdigtest\\pilot_iqvxml\\66350a76-ea36-4082-88ed-b9c9611786a1\\Protocol-2020-03-09-DOD-1.0-000001.pdf",
    protocol: "Protocol-A2",
    projectId: "",
    sponsor: "3-D Pharmaceuticals",
    indication: "ABCC6 deficiency",
    moleculeDevice: "M",
    amendment: "Y",
    isProcessing: false,
    percentComplete: "100",
    compareStatus: null,
    iqvXmlPathProc: null,
    iqvXmlPathComp: null,
    shortTitle: "",
    versionNumber: "1.3",
    documentStatus: "draft",
    draftVersion: "1.31",
    errorCode: null,
    errorReason: null,
    status: "PROCESS_COMPLETED",
    phase: "I",
    digitizedConfidenceInterval: null,
    completenessOfDigitization: null,
    protocolTitle:
      "A Phase I, Open-label Study to Assess the Safety, Tolerability, Pharmacokinetics and Anti-Tumour Activity of Adavosertib (AZD1775) in Japanese Patients with Advanced Solid Tumours",
    studyStatus: null,
    sourceSystem: null,
    environment: null,
    uploadDate: "2021-02-18T09:29:27.010000",
    timeCreated: "2021-02-18T09:29:27.010000",
    lastUpdated: "2021-02-18T09:43:46.480000",
    userCreated: null,
    userUpdated: null,
    approvalDate: "2020-03-09T00:00:00",
    isActive: true,
    nctId: null,
  },
  {
    id: "8d68a4a3-12ef-4ed1-b9e5-38537334d94a",
    userId: "1071710",
    fileName: "Protocol-2020-03-09-DOD-1.0-000001.pdf",
    documentFilePath:
      "\\\\quintiles.net\\enterprise\\Services\\protdigtest\\pilot_iqvxml\\8d68a4a3-12ef-4ed1-b9e5-38537334d94a\\Protocol-2020-03-09-DOD-1.0-000001.pdf",
    protocol: "Protocol-A2",
    projectId: "",
    sponsor: "(CKD)Chong Kun Dang Pharm",
    indication: "Zika virus disease disorder",
    moleculeDevice: "M",
    amendment: "Y",
    isProcessing: false,
    percentComplete: "100",
    compareStatus: null,
    iqvXmlPathProc: null,
    iqvXmlPathComp: null,
    shortTitle: "",
    versionNumber: "1.2",
    documentStatus: "final",
    draftVersion: null,
    errorCode: null,
    errorReason: null,
    status: "PROCESS_COMPLETED",
    phase: "I",
    digitizedConfidenceInterval: null,
    completenessOfDigitization: null,
    protocolTitle:
      "A Phase I, Open-label Study to Assess the Safety, Tolerability, Pharmacokinetics and Anti-Tumour Activity of Adavosertib (AZD1775) in Japanese Patients with Advanced Solid Tumours",
    studyStatus: null,
    sourceSystem: null,
    environment: null,
    uploadDate: "2021-02-18T07:51:48.897000",
    timeCreated: "2021-02-18T07:51:48.897000",
    lastUpdated: "2021-02-18T08:03:17.393000",
    userCreated: null,
    userUpdated: null,
    approvalDate: "2020-03-09T00:00:00",
    isActive: true,
    nctId: null,
  },
];

export const compare = {
  swap: true,
  compareId: null,
  id1: "5c2f62bf-6387-4d4e-b8c6-6e22a28dfcf5",
  protocolNumber: "Protocol-A2",
  projectId: "Protocol-A2",
  versionNumber: "1.3",
  amendmentNumber: "N",
  documentStatus: "final",
  id2: "bbc2b781-9a39-4a5f-984b-ca5562a0eb4e",
  protocolNumber2: "Protocol-A2",
  projectId2: "",
  versionNumber2: "1.2",
  amendmentNumber2: "Y",
  documentStatus2: "final",
  environment: null,
  sourceSystem: null,
  userId: null,
  requestType: null,
  iqvdata: {
    index: [
      0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
    ],
    columns: [
      "seq_num",
      "section",
      "text_type",
      "diff_type",
      "base_text",
      "compare_text",
      "char_diff",
      "confidence_score",
    ],
    data: [
      [1, "Table of Contents", "header", 1, "VERSION HISTORY", "", [], 1],
      [
        2,
        "Table of Contents",
        "text",
        0,
        "See Appendix A 5 for guidelines for the dissemination of study results.",
        "See Appendix A 5 for guidelines for the dissemination of study results.",
        [],
        1,
      ],
      [
        3,
        "Table of Contents",
        "text",
        2,
        "Lorem Ipsum is typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        [
          [15, 52],
          [367, 574],
        ],
        1,
      ],
      [
        4,
        "Table of Contents",
        "text",
        2,
        "approval protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        "Prospective approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        [
          [0, 11],
          [21, 23],
        ],
        1,
      ],
      [
        5,
        "Table of Contents",
        "text",
        2,
        "Prospective approval protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        "Prospective approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        [[21, 23]],
        1,
      ],
      [6, "Table of Contents", "header", 3, "", "TABLE OF CONTENTS", [], 1],
      [
        7,
        "Table of Contents",
        "text",
        2,
        "approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        "Prospective approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        [[0, 11]],
        1,
      ],
      [
        8,
        "Table of Contents",
        "text",
        1,
        "See Appendix A 5 for guidelines for the dissemination of study results.",
        "",
        [],
        1,
      ],
      [
        3,
        "Table of Contents",
        "header",
        2,
        "Introduction",
        "Introductions",
        [],
        1,
      ],
      [
        1,
        "Table of Contents",
        "text",
        0,
        "See Appendix A 5 for guidelines for the dissemination of study results.",
        "See Appendix A 5 for guidelines for the dissemination of study results.",
        [],
        1,
      ],
      [
        1,
        "Table of Contents",
        "text",
        2,
        "Lorem Ipsum is typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        [
          [15, 52],
          [367, 574],
        ],
        1,
      ],
      [
        1,
        "Table of Contents",
        "text",
        2,
        "approval protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        "Prospective approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        [
          [0, 11],
          [21, 23],
        ],
        1,
      ],
      [
        1,
        "Table of Contents",
        "text",
        2,
        "Prospective approval protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        "Prospective approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        [[21, 23]],
        1,
      ],
      [
        4,
        "Table of Contents",
        "header",
        0,
        "Background and rationale for conducting this study",
        "Background and rationale for conducting this study",
        [],
        1,
      ],
      [
        1,
        "Table of Contents",
        "text",
        0,
        "See Appendix A 5 for guidelines for the dissemination of study results.",
        "See Appendix A 5 for guidelines for the dissemination of study results.",
        [],
        1,
      ],
      [
        1,
        "Table of Contents",
        "text",
        2,
        "Lorem Ipsum is typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        [
          [15, 52],
          [367, 574],
        ],
        1,
      ],
      [
        1,
        "Table of Contents",
        "text",
        2,
        "approval protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        "Prospective approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        [
          [0, 11],
          [21, 23],
        ],
        1,
      ],
      [
        1,
        "Table of Contents",
        "text",
        2,
        "Prospective approval protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        "Prospective approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        [[21, 23]],
        1,
      ],
      [5, "Table of Contents", "header", 0, "Background", "Background", [], 1],
      [
        1,
        "Table of Contents",
        "text",
        3,
        "",
        "See Appendix A 5 for guidelines for the dissemination of study results.",
        [],
        1,
      ],
      [
        1,
        "Table of Contents",
        "text",
        2,
        "Lorem Ipsum is typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        [
          [15, 52],
          [367, 574],
        ],
        1,
      ],
      [
        1,
        "Table of Contents",
        "text",
        2,
        "approval protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        "Prospective approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        [
          [0, 11],
          [21, 23],
        ],
        1,
      ],
      [
        1,
        "Table of Contents",
        "text",
        2,
        "Prospective approval protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        "Prospective approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        [[21, 23]],
        1,
      ],
    ],
  },
  baseIqvXmlPath: null,
  compareIqvXmlPath: null,
  updatedIqvXmlPath:
    "\\\\quintiles.net\\enterprise\\Services\\protdigtest\\pilot_iqvxml\\5c2f62bf-6387-4d4e-b8c6-6e22a28dfcf5\\SE_OU_D2_D1_Protocol-2020-04-14-DOD-000001.20210127105907.xml.zip",
  similarityScore: 98,
};

export const initialState = {
  initialState: {
    protocol: {
      summary: {},
      view: {
        iqvdataSoa: [],
        iqvdataSummary: {},
        iqvdataToc: {
          data: [],
        },
        loader: true,
      },
      associateDocs: associateData,
      compare: {
        loading: false,
        called: false,
        iqvdata: "",
        error: false,
        message: "",
      },
    },
  },
};
export const associatedState = {
  initialState: {
    protocol: {
      summary: {},
      view: {
        iqvdataSoa: [],
        iqvdataSummary: {},
        iqvdataToc: {
          data: [],
        },
        loader: true,
      },
      associateDocs: associateData1,
      compare: {
        loading: true,
        called: true,
        iqvdata: "",
        error: false,
        message: "",
      },
    },
  },
};

export const compareState = {
  initialState: {
    protocol: {
      summary: {},
      view: {
        iqvdataSoa: [],
        iqvdataSummary: {},
        iqvdataToc: {
          data: [],
        },
        loader: true,
      },
      associateDocs: associateData1,
      compare: compare,
    },
  },
};

export const compareError = {
  initialState: {
    protocol: {
      summary: {},
      view: {
        iqvdataSoa: [],
        iqvdataSummary: {},
        iqvdataToc: {
          data: [],
        },
        loader: true,
      },
      associateDocs: associateData1,
      compare: {
        loading: false,
        called: true,
        iqvdata: "",
        error: true,
        message: "Something went Wrong",
      },
    },
  },
};

export const summary = [
  {
    id: "c498c738-a42e-4e5b-8886-b6a39ca15bf5",
    userId: "1072234",
    fileName: "272MS303 Protocol Concept Final Draft 29Oct2020_Clean.docx",
    documentFilePath:
      "\\\\quintiles.net\\enterprise\\Services\\protdigtest\\pilot_iqvxml\\c498c738-a42e-4e5b-8886-b6a39ca15bf5\\272MS303 Protocol Concept Final Draft 29Oct2020_Clean.docx",
    protocol: "SDS-DOC-TEST",
    projectId: "SDS-2",
    sponsor: "AstraZeneca",
    indication: "Heart disease",
    moleculeDevice: "SDS-2",
    amendment: "N",
    isProcessing: false,
    percentComplete: "100",
    compareStatus: null,
    iqvXmlPathProc: null,
    iqvXmlPathComp: null,
    shortTitle: "",
    versionNumber: "1.0",
    documentStatus: "final",
    draftVersion: null,
    errorCode: null,
    errorReason: null,
    status: "PROCESS_COMPLETED",
    qcStatus: "QC2",
    phase: "III",
    digitizedConfidenceInterval: null,
    completenessOfDigitization: null,
    protocolTitle:
      "Protocol Concept: Phase 3 study to evaluate the safety and TOLERABILITY of diroximEL fumarate (biib098) in adult participants From the ASIA-PACIFIC region with relapsing FORMS OF multiple sclerosis",
    studyStatus: null,
    sourceSystem: null,
    environment: null,
    uploadDate: "2021-06-29T10:08:14.133000",
    timeCreated: "2021-06-29T10:08:14.133000",
    lastUpdated: "2021-06-29T10:12:53.093000",
    userCreated: null,
    userUpdated: null,
    approvalDate: null,
    isActive: true,
    nctId: null,
  },
];
