const associateData = [
  {
    id: '66350a76-ea36-4082-88ed-b9c9611786a1',
    userId: '1071710',
    fileName: 'Protocol-2020-03-09-DOD-1.0-000001.pdf',
    documentFilePath:
      '\\\\quintiles.net\\enterprise\\Services\\protdigtest\\pilot_iqvxml\\66350a76-ea36-4082-88ed-b9c9611786a1\\Protocol-2020-03-09-DOD-1.0-000001.pdf',
    protocol: 'Protocol-A2',
    projectId: '',
    sponsor: '3-D Pharmaceuticals',
    indication: 'ABCC6 deficiency',
    moleculeDevice: 'M',
    amendment: 'Y',
    isProcessing: false,
    percentComplete: '100',
    compareStatus: null,
    iqvXmlPathProc: null,
    iqvXmlPathComp: null,
    shortTitle: '',
    versionNumber: '1.3',
    documentStatus: 'draft',
    draftVersion: '1.31',
    errorCode: null,
    errorReason: null,
    status: 'PROCESS_COMPLETED',
    phase: 'I',
    digitizedConfidenceInterval: null,
    completenessOfDigitization: null,
    protocolTitle:
      'A Phase I, Open-label Study to Assess the Safety, Tolerability, Pharmacokinetics and Anti-Tumour Activity of Adavosertib (AZD1775) in Japanese Patients with Advanced Solid Tumours',
    studyStatus: null,
    sourceSystem: null,
    environment: null,
    uploadDate: '2021-02-18T09:29:27.010000',
    timeCreated: '2021-02-18T09:29:27.010000',
    lastUpdated: '2021-02-18T09:43:46.480000',
    userCreated: null,
    userUpdated: null,
    approvalDate: '2020-03-09T00:00:00',
    isActive: true,
    nctId: null,
  },
];
const associateData1 = [
  {
    id: '66350a76-ea36-4082-88ed-b9c9611786a1',
    userId: '1071710',
    fileName: 'Protocol-2020-03-09-DOD-1.0-000001.pdf',
    documentFilePath:
      '\\\\quintiles.net\\enterprise\\Services\\protdigtest\\pilot_iqvxml\\66350a76-ea36-4082-88ed-b9c9611786a1\\Protocol-2020-03-09-DOD-1.0-000001.pdf',
    protocol: 'Protocol-A2',
    projectId: '',
    sponsor: '3-D Pharmaceuticals',
    indication: 'ABCC6 deficiency',
    moleculeDevice: 'M',
    amendment: 'Y',
    isProcessing: false,
    percentComplete: '100',
    compareStatus: null,
    iqvXmlPathProc: null,
    iqvXmlPathComp: null,
    shortTitle: '',
    versionNumber: '1.3',
    documentStatus: 'draft',
    draftVersion: '1.31',
    errorCode: null,
    errorReason: null,
    status: 'PROCESS_COMPLETED',
    phase: 'I',
    digitizedConfidenceInterval: null,
    completenessOfDigitization: null,
    protocolTitle:
      'A Phase I, Open-label Study to Assess the Safety, Tolerability, Pharmacokinetics and Anti-Tumour Activity of Adavosertib (AZD1775) in Japanese Patients with Advanced Solid Tumours',
    studyStatus: null,
    sourceSystem: null,
    environment: null,
    uploadDate: '2021-02-18T09:29:27.010000',
    timeCreated: '2021-02-18T09:29:27.010000',
    lastUpdated: '2021-02-18T09:43:46.480000',
    userCreated: null,
    userUpdated: null,
    approvalDate: '2020-03-09T00:00:00',
    isActive: true,
    nctId: null,
  },
  {
    id: '8d68a4a3-12ef-4ed1-b9e5-38537334d94a',
    userId: '1071710',
    fileName: 'Protocol-2020-03-09-DOD-1.0-000001.pdf',
    documentFilePath:
      '\\\\quintiles.net\\enterprise\\Services\\protdigtest\\pilot_iqvxml\\8d68a4a3-12ef-4ed1-b9e5-38537334d94a\\Protocol-2020-03-09-DOD-1.0-000001.pdf',
    protocol: 'Protocol-A2',
    projectId: '',
    sponsor: '(CKD)Chong Kun Dang Pharm',
    indication: 'Zika virus disease disorder',
    moleculeDevice: 'M',
    amendment: 'Y',
    isProcessing: false,
    percentComplete: '100',
    compareStatus: null,
    iqvXmlPathProc: null,
    iqvXmlPathComp: null,
    shortTitle: '',
    versionNumber: '1.2',
    documentStatus: 'final',
    draftVersion: null,
    errorCode: null,
    errorReason: null,
    status: 'PROCESS_COMPLETED',
    phase: 'I',
    digitizedConfidenceInterval: null,
    completenessOfDigitization: null,
    protocolTitle:
      'A Phase I, Open-label Study to Assess the Safety, Tolerability, Pharmacokinetics and Anti-Tumour Activity of Adavosertib (AZD1775) in Japanese Patients with Advanced Solid Tumours',
    studyStatus: null,
    sourceSystem: null,
    environment: null,
    uploadDate: '2021-02-18T07:51:48.897000',
    timeCreated: '2021-02-18T07:51:48.897000',
    lastUpdated: '2021-02-18T08:03:17.393000',
    userCreated: null,
    userUpdated: null,
    approvalDate: '2020-03-09T00:00:00',
    isActive: true,
    nctId: null,
  },
];

export const compare = {
  swap: true,
  compareId: null,
  id1: '5c2f62bf-6387-4d4e-b8c6-6e22a28dfcf5',
  protocolNumber: 'Protocol-A2',
  projectId: 'Protocol-A2',
  versionNumber: '1.3',
  amendmentNumber: 'N',
  documentStatus: 'final',
  id2: 'bbc2b781-9a39-4a5f-984b-ca5562a0eb4e',
  protocolNumber2: 'Protocol-A2',
  projectId2: '',
  versionNumber2: '1.2',
  amendmentNumber2: 'Y',
  documentStatus2: 'final',
  environment: null,
  sourceSystem: null,
  userId: null,
  requestType: null,
  iqvdata: {
    index: [
      0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
    ],
    columns: [
      'seq_num',
      'section',
      'text_type',
      'diff_type',
      'base_text',
      'compare_text',
      'char_diff',
      'confidence_score',
    ],
    data: [
      [1, 'Table of Contents', 'header', 1, 'VERSION HISTORY', '', [], 1],
      [
        2,
        'Table of Contents',
        'text',
        0,
        'See Appendix A 5 for guidelines for the dissemination of study results.',
        'See Appendix A 5 for guidelines for the dissemination of study results.',
        [],
        1,
      ],
      [
        3,
        'Table of Contents',
        'text',
        2,
        "Lorem Ipsum is typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        [
          [15, 52],
          [367, 574],
        ],
        1,
      ],
      [
        4,
        'Table of Contents',
        'text',
        2,
        'approval protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.',
        'Prospective approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.',
        [
          [0, 11],
          [21, 23],
        ],
        1,
      ],
      [
        5,
        'Table of Contents',
        'text',
        2,
        'Prospective approval protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.',
        'Prospective approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.',
        [[21, 23]],
        1,
      ],
      [6, 'Table of Contents', 'header', 3, '', 'TABLE OF CONTENTS', [], 1],
      [
        7,
        'Table of Contents',
        'text',
        2,
        'approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.',
        'Prospective approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.',
        [[0, 11]],
        1,
      ],
      [
        8,
        'Table of Contents',
        'text',
        1,
        'See Appendix A 5 for guidelines for the dissemination of study results.',
        '',
        [],
        1,
      ],
      [
        3,
        'Table of Contents',
        'header',
        2,
        'Introduction',
        'Introductions',
        [],
        1,
      ],
      [
        1,
        'Table of Contents',
        'text',
        0,
        'See Appendix A 5 for guidelines for the dissemination of study results.',
        'See Appendix A 5 for guidelines for the dissemination of study results.',
        [],
        1,
      ],
      [
        1,
        'Table of Contents',
        'text',
        2,
        "Lorem Ipsum is typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        [
          [15, 52],
          [367, 574],
        ],
        1,
      ],
      [
        1,
        'Table of Contents',
        'text',
        2,
        'approval protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.',
        'Prospective approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.',
        [
          [0, 11],
          [21, 23],
        ],
        1,
      ],
      [
        1,
        'Table of Contents',
        'text',
        2,
        'Prospective approval protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.',
        'Prospective approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.',
        [[21, 23]],
        1,
      ],
      [
        4,
        'Table of Contents',
        'header',
        0,
        'Background and rationale for conducting this study',
        'Background and rationale for conducting this study',
        [],
        1,
      ],
      [
        1,
        'Table of Contents',
        'text',
        0,
        'See Appendix A 5 for guidelines for the dissemination of study results.',
        'See Appendix A 5 for guidelines for the dissemination of study results.',
        [],
        1,
      ],
      [
        1,
        'Table of Contents',
        'text',
        2,
        "Lorem Ipsum is typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        [
          [15, 52],
          [367, 574],
        ],
        1,
      ],
      [
        1,
        'Table of Contents',
        'text',
        2,
        'approval protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.',
        'Prospective approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.',
        [
          [0, 11],
          [21, 23],
        ],
        1,
      ],
      [
        1,
        'Table of Contents',
        'text',
        2,
        'Prospective approval protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.',
        'Prospective approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.',
        [[21, 23]],
        1,
      ],
      [5, 'Table of Contents', 'header', 0, 'Background', 'Background', [], 1],
      [
        1,
        'Table of Contents',
        'text',
        3,
        '',
        'See Appendix A 5 for guidelines for the dissemination of study results.',
        [],
        1,
      ],
      [
        1,
        'Table of Contents',
        'text',
        2,
        "Lorem Ipsum is typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        [
          [15, 52],
          [367, 574],
        ],
        1,
      ],
      [
        1,
        'Table of Contents',
        'text',
        2,
        'approval protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.',
        'Prospective approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.',
        [
          [0, 11],
          [21, 23],
        ],
        1,
      ],
      [
        1,
        'Table of Contents',
        'text',
        2,
        'Prospective approval protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.',
        'Prospective approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.',
        [[21, 23]],
        1,
      ],
    ],
  },
  baseIqvXmlPath: null,
  compareIqvXmlPath: null,
  updatedIqvXmlPath:
    '\\\\quintiles.net\\enterprise\\Services\\protdigtest\\pilot_iqvxml\\5c2f62bf-6387-4d4e-b8c6-6e22a28dfcf5\\SE_OU_D2_D1_Protocol-2020-04-14-DOD-000001.20210127105907.xml.zip',
  similarityScore: 98,
};

export const initialState = {
  initialState: {
    protocol: {
      summary: {},
      view: {
        iqvdataSoa: [],
        iqvdataSummary: {},
        iqvdataToc: {
          data: [],
        },
        loader: true,
      },
      associateDocs: associateData,
      compare: {
        loading: false,
        called: false,
        iqvdata: '',
        error: false,
        message: '',
      },
    },
  },
};
export const associatedState = {
  initialState: {
    protocol: {
      summary: {},
      view: {
        iqvdataSoa: [],
        iqvdataSummary: {},
        iqvdataToc: {
          data: [],
        },
        loader: true,
      },
      associateDocs: associateData1,
      compare: {
        loading: true,
        called: true,
        iqvdata: '',
        error: false,
        message: '',
      },
    },
  },
};

export const compareState = {
  initialState: {
    protocol: {
      summary: {},
      view: {
        iqvdataSoa: [],
        iqvdataSummary: {},
        iqvdataToc: {
          data: [],
        },
        loader: true,
      },
      associateDocs: associateData1,
      compare,
    },
  },
};

export const compareError = {
  initialState: {
    protocol: {
      summary: {},
      view: {
        iqvdataSoa: [],
        iqvdataSummary: {},
        iqvdataToc: {
          data: [],
        },
        loader: true,
      },
      associateDocs: associateData1,
      compare: {
        loading: false,
        called: true,
        iqvdata: '',
        error: true,
        message: 'Something went Wrong',
      },
    },
  },
};

export const summary = [
  {
    id: 'c498c738-a42e-4e5b-8886-b6a39ca15bf5',
    userId: '1072234',
    fileName: '272MS303 Protocol Concept Final Draft 29Oct2020_Clean.docx',
    documentFilePath:
      '\\\\quintiles.net\\enterprise\\Services\\protdigtest\\pilot_iqvxml\\c498c738-a42e-4e5b-8886-b6a39ca15bf5\\272MS303 Protocol Concept Final Draft 29Oct2020_Clean.docx',
    protocol: 'SDS-DOC-TEST',
    projectId: 'SDS-2',
    sponsor: 'AstraZeneca',
    indication: 'Heart disease',
    moleculeDevice: 'SDS-2',
    amendment: 'N',
    isProcessing: false,
    percentComplete: '100',
    compareStatus: null,
    iqvXmlPathProc: null,
    iqvXmlPathComp: null,
    shortTitle: '',
    versionNumber: '1.0',
    documentStatus: 'final',
    draftVersion: null,
    errorCode: null,
    errorReason: null,
    status: 'PROCESS_COMPLETED',
    qcStatus: 'QC2',
    phase: 'III',
    digitizedConfidenceInterval: null,
    completenessOfDigitization: null,
    protocolTitle:
      'Protocol Concept: Phase 3 study to evaluate the safety and TOLERABILITY of diroximEL fumarate (biib098) in adult participants From the ASIA-PACIFIC region with relapsing FORMS OF multiple sclerosis',
    studyStatus: null,
    sourceSystem: null,
    environment: null,
    uploadDate: '2021-06-29T10:08:14.133000',
    timeCreated: '2021-06-29T10:08:14.133000',
    lastUpdated: '2021-06-29T10:12:53.093000',
    userCreated: null,
    userUpdated: null,
    approvalDate: null,
    isActive: true,
    nctId: null,
  },
  {
    id: '00d9456f-b5d3-4045-b76f-3bdecbe99775',
    userId: '1138076',
    fileName: 'NCT02973100.pdf',
    documentFilePath:
      '\\\\quintiles.net\\enterprise\\Services\\protdigtest\\pilot_iqvxml\\00d9456f-b5d3-4045-b76f-3bdecbe99775\\NCT02973100.pdf',
    protocol: 'SDS-DOC-NCT02973100.pdf.cd93144c-1b57-4848-a197-0e53b9938827',
    projectId: 'pid',
    sponsor: '',
    indication: '',
    moleculeDevice: '',
    amendment: '',
    isProcessing: false,
    percentComplete: '100',
    compareStatus: null,
    iqvXmlPathProc: null,
    iqvXmlPathComp: null,
    shortTitle: '',
    versionNumber: '1.0',
    documentStatus: 'final',
    draftVersion: null,
    errorCode: null,
    errorReason: null,
    status: 'PROCESS_COMPLETED',
    qcStatus: 'QC2',
    phase: 'III',
    digitizedConfidenceInterval: null,
    completenessOfDigitization: null,
    protocolTitle: '',
    studyStatus: null,
    sourceSystem: null,
    environment: null,
    uploadDate: '2021-06-29T10:08:14.133000',
    timeCreated: '2021-06-29T10:08:14.133000',
    lastUpdated: '2021-06-29T10:12:53.093000',
    userCreated: null,
    userUpdated: null,
    approvalDate: null,
    isActive: true,
    nctId: null,
  },
];

export const headersList = [
  {
    doc_id: '574051fb-1cb5-4e6c-816c-f9964090a1e7',
    group_type: 'DocumentLinks',
    link_id: '65a5685c-8836-11ed-989e-005056ab6469',
    LinkLevel: 1,
    page: 1,
    sec_id: '',
    source_file_section:
      'The Multi-National Gilenya® Pregnancy Exposure Registry in Multiple Sclerosis',
    LinkType: 'toc',
    qc_change_type: '',
    sequence: 0,
    section_locked: false,
    audit_info: {
      last_reviewed_date: '',
      last_reviewed_by: '',
      total_no_review: '',
    },
  },
  {
    doc_id: '574051fb-1cb5-4e6c-816c-f9964090a1e7',
    group_type: 'DocumentLinks',
    link_id: '65a56866-8836-11ed-a073-005056ab6469',
    LinkLevel: 1,
    page: 10,
    sec_id: '1',
    source_file_section: '1 Background and rationale',
    LinkType: 'toc',
    qc_change_type: '',
    sequence: 10,
    section_locked: false,
    audit_info: {
      last_reviewed_date: '',
      last_reviewed_by: '',
      total_no_review: '',
    },
  },
];

export const metaVariables = [
  {
    display_name: 'Is Active',
    attr_name: 'isActive',
    attr_value: true,
    id: 1,
    isCustom: false,
  },
  {
    display_name: 'Id',
    attr_name: 'id',
    attr_value: '0be44992-9573-4010-962c-de1a1b18b08d',
    id: 2,
    isCustom: false,
  },
  {
    display_name: 'User Id',
    attr_name: 'userId',
    attr_value: 'test2',
    id: 3,
    isCustom: false,
  },
  {
    display_name: 'File Name',
    attr_name: 'fileName',
    attr_value: 'SP-1011-002 Protocol-2017-03-21-VER-Core-000001.pdf',
    id: 4,
    isCustom: false,
  },
  {
    display_name: 'Document File Path',
    attr_name: 'documentFilePath',
    attr_value: 'false',
    id: 5,
    isCustom: false,
  },
  {
    display_name: 'Protocol',
    attr_name: 'protocol',
    attr_value: 'sp.b4b8bd0c-bd6f-4b35-b73b-dff06bfcfcbc',
    id: 6,
    isCustom: false,
  },
  {
    display_name: 'Project Id',
    attr_name: 'projectId',
    attr_value: 'pid',
    id: 7,
    isCustom: false,
  },
  {
    display_name: 'Sponsor',
    attr_name: 'sponsor',
    attr_value: 's1',
    id: 8,
    isCustom: false,
  },
  {
    display_name: 'Indication',
    attr_name: 'indication',
    attr_value: 'ind',
    id: 9,
    isCustom: false,
  },
  {
    display_name: 'Molecule Device',
    attr_name: 'moleculeDevice',
    attr_value: 'mol',
    id: 10,
    isCustom: false,
  },
  {
    display_name: 'Amendment',
    attr_name: 'amendment',
    attr_value: 'Y',
    id: 11,
    isCustom: false,
  },
  {
    display_name: 'Version Number',
    attr_name: 'versionNumber',
    attr_value: 'v3',
    id: 12,
    isCustom: false,
  },
  {
    display_name: 'Document Status',
    attr_name: 'documentStatus',
    attr_value: 'final',
    id: 13,
    isCustom: false,
  },
  {
    display_name: 'Draft Version',
    attr_name: 'draftVersion',
    attr_value: null,
    id: 14,
    isCustom: false,
  },
  {
    display_name: 'Upload Date',
    attr_name: 'uploadDate',
    attr_value: '2022-11-20 02:35:12.760000',
    id: 15,
    isCustom: false,
  },
  {
    display_name: 'Is Processing',
    attr_name: 'isProcessing',
    attr_value: false,
    id: 16,
    isCustom: false,
  },
  {
    display_name: 'Error Code',
    attr_name: 'errorCode',
    attr_value: null,
    id: 17,
    isCustom: false,
  },
  {
    display_name: 'Error Reason',
    attr_name: 'errorReason',
    attr_value: null,
    id: 18,
    isCustom: false,
  },
  {
    display_name: 'Percent Complete',
    attr_name: 'percentComplete',
    attr_value: '100',
    id: 19,
    isCustom: false,
  },
  {
    display_name: 'Status',
    attr_name: 'status',
    attr_value: 'PROCESS_COMPLETED',
    id: 20,
    isCustom: false,
  },
  {
    display_name: 'Qc Status',
    attr_name: 'qcStatus',
    attr_value: 'QC_NOT_STARTED',
    id: 21,
    isCustom: false,
  },
  {
    display_name: 'Run Id',
    attr_name: 'runId',
    attr_value: 0,
    id: 22,
    isCustom: false,
  },
  {
    display_name: 'Compare Status',
    attr_name: 'compareStatus',
    attr_value: null,
    id: 23,
    isCustom: false,
  },
  {
    display_name: 'Iqv Xml Path Proc',
    attr_name: 'iqvXmlPathProc',
    attr_value: null,
    id: 24,
    isCustom: false,
  },
  {
    display_name: 'Iqv Xml Path Comp',
    attr_name: 'iqvXmlPathComp',
    attr_value: null,
    id: 25,
    isCustom: false,
  },
  {
    display_name: 'Protocol Title',
    attr_name: 'protocolTitle',
    attr_value:
      'FLUTicasone in Eosinophilic esophagitis (FLUTE):  A Randomized, Double-blind, Placebo-controlled, Dose-ranging, and Maintenance Study of APT-1011 in Subjects with Eosinophilic Esophagitis',
    id: 26,
    isCustom: false,
  },
  {
    display_name: 'Short Title',
    attr_name: 'shortTitle',
    attr_value: '',
    id: 27,
    isCustom: false,
  },
  {
    display_name: 'Phase',
    attr_name: 'phase',
    attr_value: 'IIb',
    id: 28,
    isCustom: false,
  },
  {
    display_name: 'Digitized Confidence Interval',
    attr_name: 'digitizedConfidenceInterval',
    attr_value: null,
    id: 29,
    isCustom: false,
  },
  {
    display_name: 'Completeness Of Digitization',
    attr_name: 'completenessOfDigitization',
    attr_value: null,
    id: 30,
    isCustom: false,
  },
  {
    display_name: 'Approval Date',
    attr_name: 'approvalDate',
    attr_value: null,
    id: 31,
    isCustom: false,
  },
  {
    display_name: 'Study Status',
    attr_name: 'studyStatus',
    attr_value: 'stat',
    id: 32,
    isCustom: false,
  },
  {
    display_name: 'Source System',
    attr_name: 'sourceSystem',
    attr_value: 'sys',
    id: 33,
    isCustom: false,
  },
  {
    display_name: 'Environment',
    attr_name: 'environment',
    attr_value: 'env',
    id: 34,
    isCustom: false,
  },
  {
    display_name: 'Nct Id',
    attr_name: 'nctId',
    attr_value: null,
    id: 35,
    isCustom: false,
  },
  {
    display_name: 'Time Created',
    attr_name: 'timeCreated',
    attr_value: '2022-11-20 02:35:12.760000',
    id: 36,
    isCustom: false,
  },
  {
    display_name: 'Last Updated',
    attr_name: 'lastUpdated',
    attr_value: '2022-11-20 09:07:07.707000',
    id: 37,
    isCustom: false,
  },
  {
    display_name: 'User Created',
    attr_name: 'userCreated',
    attr_value: null,
    id: 38,
    isCustom: false,
  },
  {
    display_name: 'User Updated',
    attr_name: 'userUpdated',
    attr_value: '2023-02-03 09:07:07.707000',
    id: 39,
    isCustom: false,
  },
  {
    display_name: 'New',
    attr_name: 'new',
    attr_type: 'string',
    attr_value: 'data',
    confidence: null,
    note: null,
    id: 1,
    isCustom: true,
  },
  {
    display_name: 'Boolean Test',
    attr_name: 'boolean_test',
    attr_type: 'boolean',
    attr_value: true,
    confidence: null,
    note: null,
    id: 2,
    isCustom: true,
  },
  {
    display_name: 'Custom Key2',
    attr_name: 'custom_key2',
    attr_type: 'date',
    attr_value: '2023-02-03 00:00:00',
    confidence: null,
    note: null,
    id: 3,
    isCustom: true,
  },
  {
    display_name: 'Custom Key',
    attr_name: 'custom_key',
    attr_type: 'string',
    attr_value: 'test2',
    confidence: null,
    note: null,
    id: 4,
    isCustom: true,
  },
  {
    display_name: 'Version Date',
    attr_name: 'version_date',
    attr_type: 'date',
    attr_value: '2018-12-01 00:00:00',
    confidence: null,
    note: null,
    id: 5,
    isCustom: true,
  },
  {
    display_name: 'Document Status',
    attr_name: 'documentStatus',
    attr_type: 'string',
    attr_value: 'Draft',
    confidence: null,
    note: null,
    id: 6,
    isCustom: true,
  },
];

export const dataValues = {
  amendment: 'Y',
  amendmentNumber: null,
  approvalDate: null,
  compareStatus: null,
  completenessOfDigitization: null,
  digitizedConfidenceInterval: null,
  documentFilePath:
    '\\\\quintiles.net\\enterprise\\Services\\protdigtest\\pilot_iqvxml\\f2571c30-a39f-4d58-a092-09edaac5b814\\NCT03399370 (1).pdf',
  documentStatus: 'draft',
  draftVersion: null,
  environment: null,
  errorCode: null,
  errorReason: null,
  fileName: 'NCT03399370 (1).pdf',
  id: 'f2571c30-a39f-4d58-a092-09edaac5b814',
  indication: null,
  iqvXmlPathComp: null,
  iqvXmlPathProc: null,
  isActive: true,
  isProcessing: false,
  lastUpdated: '2023-04-17T10:06:27.899757',
  moleculeDevice: null,
  nctId: null,
  percentComplete: '100',
  phase: 'III',
  projectId: '',
  protocol: 'K-877-3.01CH',
  protocolTitle:
    'Title of Study : A placebo-controlled, double-blind, randomized trial to evaluate the effect of 300 mg of inclisiran sodium given as subcutaneous injections in subjects with atherosclerotic cardiovascular disease (ASCVD) and elevated low-density lipoprotein cholesterol (LDL-C) Title of Study : A placebo-controlled, double-blind, randomized trial to evaluate the effect of 300 mg of inclisiran sodium given as subcutaneous injections in subjects with atherosclerotic cardiovascular disease (ASCVD) and elevated low-density lipoprotein cholesterol (LDL-C)',
  qcStatus: 'QC_NOT_STARTED',
  redactProfile: 'profile_1',
  shortTitle: '',
  sourceSystem: null,
  sponsor: null,
  status: 'PROCESS_COMPLETED',
  studyStatus: null,
  timeCreated: '2023-04-17T10:06:27.899757',
  uploadDate: '2023-04-17T10:06:27.899757',
  userCreated: null,
  userFollowingFlag: false,
  userId: '1150903',
  userPrimaryRoleFlag: true,
  userUpdated: null,
  userUploadedFlag: false,
  versionNumber: '01',
};

export const preloadedData = {
  initialState: {
    user: {
      userDetail: {
        userId: 'u123456',
        username: 'test',
        email: 'test@iqvia.com',
        user_type: 'normal',
      },
    },
    protocol: {
      rightBladeValue: 'Protocol Attributes',
      activeTOC: ['bc4dc374-8a78-11ed-af64-005056ab6469'],
      protocolTocData: {
        success: true,
        data: [
          {
            doc_id: 'f2571c30-a39f-4d58-a092-09edaac5b814',
            group_type: 'DocumentLinks',
            link_id: 'bc4dc374-8a78-11ed-af64-005056ab6469',
            LinkLevel: 1,
            page: 0,
            sec_id: '',
            source_file_section: 'TITLE PAGE',
            LinkType: 'toc',
            line_id: 'f2571c30-a39f-4d58-a092-09edaac5b814',
            preferred_term: '',
            qc_change_type: '',
            sequence: 0,
            section_locked: false,
            audit_info: {
              last_reviewed_date: '17-04-2023',
              last_reviewed_by: '',
              total_no_review: 1,
            },
            linkandReference: 'test',
          },
        ],
      },
      summary: {
        loading: false,
        success: true,
        data: {
          id: 'f2571c30-a39f-4d58-a092-09edaac5b814',
          userId: '1150903',
          fileName: 'NCT03399370 (1).pdf',
          documentFilePath:
            '\\\\quintiles.net\\enterprise\\Services\\protdigtest\\pilot_iqvxml\\f2571c30-a39f-4d58-a092-09edaac5b814\\NCT03399370 (1).pdf',
          protocol: 'K-877-3.01CH',
          projectId: '',
          sponsor: null,
          indication: null,
          moleculeDevice: null,
          amendment: 'Y',
          isProcessing: false,
          percentComplete: '100',
          compareStatus: null,
          iqvXmlPathProc: null,
          iqvXmlPathComp: null,
          shortTitle: '',
          versionNumber: '01',
          documentStatus: 'draft',
          draftVersion: null,
          errorCode: null,
          errorReason: null,
          status: 'PROCESS_COMPLETED',
          qcStatus: 'QC_NOT_STARTED',
          phase: 'III',
          digitizedConfidenceInterval: null,
          completenessOfDigitization: null,
          protocolTitle:
            'Title of Study : A placebo-controlled, double-blind, randomized trial to evaluate the effect of 300 mg of inclisiran sodium given as subcutaneous injections in subjects with atherosclerotic cardiovascular disease (ASCVD) and elevated low-density lipoprotein cholesterol (LDL-C) Title of Study : A placebo-controlled, double-blind, randomized trial to evaluate the effect of 300 mg of inclisiran sodium given as subcutaneous injections in subjects with atherosclerotic cardiovascular disease (ASCVD) and elevated low-density lipoprotein cholesterol (LDL-C)',
          studyStatus: null,
          sourceSystem: null,
          environment: null,
          uploadDate: '2023-04-17T10:06:27.899757',
          timeCreated: '2023-04-17T10:06:27.899757',
          lastUpdated: '2023-04-17T10:06:27.899757',
          userCreated: null,
          userUpdated: null,
          approvalDate: null,
          isActive: true,
          nctId: null,
          amendmentNumber: null,
          redactProfile: 'profile_1',
          userUploadedFlag: false,
          userPrimaryRoleFlag: false,
          userFollowingFlag: false,
          wfData: [
            {
              id: 'f2571c30-a39f-4d58-a092-09edaac5b814',
              wfId: 'f2571c30-a39f-4d58-a092-09edaac5b814',
              wfStatus: 'COMPLETED',
              wfAllServices: [
                'triage',
                'digitizer1',
                'digitizer2',
                'extraction',
                'digitizer2_omopgenerate',
                'i2e_omop_update',
                'digitizer2_omopupdate',
                'digitizer2_compare',
                'meta_tagging',
                'meta_extraction',
                'analyzer',
                'es_ingestion',
                'email_notification',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
              ],
              wfName: 'full_flow',
              wfRunningServices: [],
              wfErrorMessageDetails: '',
              wfFinishedServices: [
                'triage',
                'digitizer1',
                'digitizer2',
                'extraction',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'i2e_omop_update',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_omopupdate',
                'es_ingestion',
                'meta_tagging',
                'meta_extraction',
                'email_notification',
              ],
              wfPercentComplete: 100,
              timeCreated: '17-Apr-2023',
            },
          ],
        },
      },
      sectionIndex: 0,
      TOCActiveAccordion: [true, false],
      sectionDetails: {
        protocol: '15-07',
        sectionResponse: {
          success: true,
        },
        data: [
          {
            linkId: 'bc4dc374-8a78-11ed-af64-005056ab6469',
            data: [
              {
                section_level: '',
                CPT_section: 'Unmapped',
                type: 'text',
                content: 'CONFIDENTIAL',
                link_and_reference: { 0: 'source_text' },
                font_info: {
                  IsBold: false,
                  font_size: -1,
                  font_style: '',
                  entity: [],
                  roi_id: {
                    para: 'bc5080ba-8a78-11ed-8986-005056ab6469',
                    childbox: '',
                    subtext: '',
                  },
                },
                level_1_CPT_section: 'Unmapped',
                file_section: 'Unmapped',
                file_section_num: '',
                file_section_level: 1,
                seq_num: 2,
                qc_change_type: '',
                line_id: 'bc5080ba-8a78-11ed-8986-005056ab6469',
                aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
                synonyms_extracted_terms: '',
                semantic_extraction: '',
                section_locked: false,
                clinical_terms: {
                  CONFIDENTIAL: {
                    synonyms: 'value1, value2',
                  },
                },
              },
              {
                section_level: '',
                CPT_section: 'Unmapped',
                type: 'text',
                content: 'PLASMA',
                link_and_reference: { 0: 'source_text' },
                font_info: {
                  italics: true,
                  IsBold: true,
                  font_size: -1,
                  font_style: '',
                  entity: [],
                  roi_id: {
                    para: 'bc5080ba-8a78-11ed-8986-005056ab6469',
                    childbox: '',
                    subtext: '',
                  },
                },
                level_1_CPT_section: 'Unmapped',
                file_section: 'Unmapped',
                file_section_num: '',
                file_section_level: 1,
                seq_num: 2,
                qc_change_type: '',
                line_id: 'bc5080ba-8a78-11ed-8986-005056ab6469',
                aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
                synonyms_extracted_terms: '',
                semantic_extraction: '',
                section_locked: false,
                clinical_terms: {
                  CONFIDENTIAL: {
                    synonyms: 'value1, value2',
                  },
                },
              },
            ],
          },
          {
            linkId: 'bc4dc375-8a78-11ed-946e-005056ab6469',
            data: [
              {
                section_level: '',
                CPT_section: 'Unmapped',
                type: 'text',
                content: 'PLASMA',
                font_info: {
                  italics: true,
                  IsBold: true,
                  font_size: -1,
                  font_style: '',
                  entity: [],
                  roi_id: {
                    para: 'bc4dc375-8a78-11ed-946e-005056ab6469',
                    childbox: '',
                    subtext: '',
                  },
                },
                level_1_CPT_section: 'Unmapped',
                file_section: 'Unmapped',
                file_section_num: '',
                file_section_level: 1,
                seq_num: 2,
                qc_change_type: '',
                line_id: 'bc5A80ba-8a78-11ed-8986-005056ab6469',
                aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
                synonyms_extracted_terms: '',
                semantic_extraction: '',
                section_locked: false,
                clinical_terms: {
                  CONFIDENTIAL: {
                    synonyms: 'value1, value2',
                  },
                },
              },
            ],
          },
        ],
        sections: [
          {
            section_level: '',
            CPT_section: 'Unmapped',
            type: 'text',
            content: 'CONFIDENTIAL',
            font_info: {
              IsBold: false,
              font_size: -1,
              font_style: '',
              entity: [],
              roi_id: {
                para: 'bc4dc375-8a78-11ed-946e-005056ab6469',
                childbox: '',
                subtext: '',
              },
            },
            level_1_CPT_section: 'Unmapped',
            file_section: 'Unmapped',
            file_section_num: '',
            file_section_level: 1,
            seq_num: 2,
            qc_change_type: '',
            line_id: 'bc5C80ba-8a78-11ed-8986-005056ab6469',
            aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
            synonyms_extracted_terms: '',
            semantic_extraction: '',
            section_locked: false,
            clinical_terms: {
              CONFIDENTIAL: {
                synonyms: 'value1, value2',
              },
            },
          },
          {
            section_level: '',
            CPT_section: 'Unmapped',
            type: 'text',
            content: 'PLASMA',
            font_info: {
              italics: true,
              IsBold: true,
              font_size: -1,
              font_style: '',
              entity: [],
              roi_id: {
                para: 'bc4dc375-8a78-11ed-946e-005056ab6469',
                childbox: '',
                subtext: '',
              },
            },
            level_1_CPT_section: 'Unmapped',
            file_section: 'Unmapped',
            file_section_num: '',
            file_section_level: 1,
            seq_num: 2,
            qc_change_type: '',
            line_id: 'bc5CA0ba-8a78-11ed-8986-005056ab6469',
            aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
            synonyms_extracted_terms: '',
            semantic_extraction: '',
            section_locked: false,
            clinical_terms: {
              CONFIDENTIAL: {
                synonyms: 'value1, value2',
              },
            },
          },
        ],
      },
    },
  },
};

export const preloadedDataForLab = {
  initialState: {
    user: {
      userDetail: {
        userId: 'u123456',
        username: 'test',
        email: 'test@iqvia.com',
        user_type: 'normal',
      },
    },
    protocol: {
      rightBladeValue: 'Lab Data',
      activeTOC: ['bc4dc374-8a78-11ed-af64-005056ab6469'],
      protocolTocData: {
        success: true,
        data: [
          {
            doc_id: 'f2571c30-a39f-4d58-a092-09edaac5b814',
            group_type: 'DocumentLinks',
            link_id: 'bc4dc374-8a78-11ed-af64-005056ab6469',
            LinkLevel: 1,
            page: 0,
            sec_id: '',
            source_file_section: 'TITLE PAGE',
            LinkType: 'toc',
            line_id: 'f2571c30-a39f-4d58-a092-09edaac5b814',
            preferred_term: '',
            qc_change_type: '',
            sequence: 0,
            section_locked: false,
            audit_info: {
              last_reviewed_date: '17-04-2023',
              last_reviewed_by: '',
              total_no_review: 1,
            },
            linkandReference: 'test',
          },
        ],
      },
      summary: {
        loading: false,
        success: true,
        data: {
          id: 'f2571c30-a39f-4d58-a092-09edaac5b814',
          userId: '1150903',
          fileName: 'NCT03399370 (1).pdf',
          documentFilePath:
            '\\\\quintiles.net\\enterprise\\Services\\protdigtest\\pilot_iqvxml\\f2571c30-a39f-4d58-a092-09edaac5b814\\NCT03399370 (1).pdf',
          protocol: 'K-877-3.01CH',
          projectId: '',
          sponsor: null,
          indication: null,
          moleculeDevice: null,
          amendment: 'Y',
          isProcessing: false,
          percentComplete: '100',
          compareStatus: null,
          iqvXmlPathProc: null,
          iqvXmlPathComp: null,
          shortTitle: '',
          versionNumber: '01',
          documentStatus: 'draft',
          draftVersion: null,
          errorCode: null,
          errorReason: null,
          status: 'PROCESS_COMPLETED',
          qcStatus: 'QC_NOT_STARTED',
          phase: 'III',
          digitizedConfidenceInterval: null,
          completenessOfDigitization: null,
          protocolTitle:
            'Title of Study : A placebo-controlled, double-blind, randomized trial to evaluate the effect of 300 mg of inclisiran sodium given as subcutaneous injections in subjects with atherosclerotic cardiovascular disease (ASCVD) and elevated low-density lipoprotein cholesterol (LDL-C) Title of Study : A placebo-controlled, double-blind, randomized trial to evaluate the effect of 300 mg of inclisiran sodium given as subcutaneous injections in subjects with atherosclerotic cardiovascular disease (ASCVD) and elevated low-density lipoprotein cholesterol (LDL-C)',
          studyStatus: null,
          sourceSystem: null,
          environment: null,
          uploadDate: '2023-04-17T10:06:27.899757',
          timeCreated: '2023-04-17T10:06:27.899757',
          lastUpdated: '2023-04-17T10:06:27.899757',
          userCreated: null,
          userUpdated: null,
          approvalDate: null,
          isActive: true,
          nctId: null,
          amendmentNumber: null,
          redactProfile: 'profile_1',
          userUploadedFlag: false,
          userPrimaryRoleFlag: false,
          userFollowingFlag: false,
          wfData: [
            {
              id: 'f2571c30-a39f-4d58-a092-09edaac5b814',
              wfId: 'f2571c30-a39f-4d58-a092-09edaac5b814',
              wfStatus: 'COMPLETED',
              wfAllServices: [
                'triage',
                'digitizer1',
                'digitizer2',
                'extraction',
                'digitizer2_omopgenerate',
                'i2e_omop_update',
                'digitizer2_omopupdate',
                'digitizer2_compare',
                'meta_tagging',
                'meta_extraction',
                'analyzer',
                'es_ingestion',
                'email_notification',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
              ],
              wfName: 'full_flow',
              wfRunningServices: [],
              wfErrorMessageDetails: '',
              wfFinishedServices: [
                'triage',
                'digitizer1',
                'digitizer2',
                'extraction',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'i2e_omop_update',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_omopupdate',
                'es_ingestion',
                'meta_tagging',
                'meta_extraction',
                'email_notification',
              ],
              wfPercentComplete: 100,
              timeCreated: '17-Apr-2023',
            },
          ],
        },
      },
      sectionIndex: 0,
      TOCActiveAccordion: [true, false],
      sectionDetails: {
        protocol: '15-07',
        sectionResponse: {
          success: true,
        },
        data: [
          {
            linkId: 'bc4dc374-8a78-11ed-af64-005056ab6469',
            data: [
              {
                section_level: '',
                CPT_section: 'Unmapped',
                type: 'text',
                content: 'CONFIDENTIAL',
                link_and_reference: { 0: 'source_text' },
                font_info: {
                  IsBold: false,
                  font_size: -1,
                  font_style: '',
                  entity: [],
                  roi_id: {
                    para: 'bc5080ba-8a78-11ed-8986-005056ab6469',
                    childbox: '',
                    subtext: '',
                  },
                },
                level_1_CPT_section: 'Unmapped',
                file_section: 'Unmapped',
                file_section_num: '',
                file_section_level: 1,
                seq_num: 2,
                qc_change_type: '',
                line_id: 'bc5080ba-8a78-11ed-8986-005056ab6469',
                aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
                synonyms_extracted_terms: '',
                semantic_extraction: '',
                section_locked: false,
                clinical_terms: {
                  CONFIDENTIAL: {
                    synonyms: 'value1, value2',
                  },
                },
              },
              {
                section_level: '',
                CPT_section: 'Unmapped',
                type: 'text',
                content: 'PLASMA',
                link_and_reference: { 0: 'source_text' },
                font_info: {
                  italics: true,
                  IsBold: true,
                  font_size: -1,
                  font_style: '',
                  entity: [],
                  roi_id: {
                    para: 'bc5080ba-8a78-11ed-8986-005056ab6469',
                    childbox: '',
                    subtext: '',
                  },
                },
                level_1_CPT_section: 'Unmapped',
                file_section: 'Unmapped',
                file_section_num: '',
                file_section_level: 1,
                seq_num: 2,
                qc_change_type: '',
                line_id: 'bc5080ba-8a78-11ed-8986-005056ab6469',
                aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
                synonyms_extracted_terms: '',
                semantic_extraction: '',
                section_locked: false,
                clinical_terms: {
                  CONFIDENTIAL: {
                    synonyms: 'value1, value2',
                  },
                },
              },
            ],
          },
          {
            linkId: 'bc4dc375-8a78-11ed-946e-005056ab6469',
            data: [
              {
                section_level: '',
                CPT_section: 'Unmapped',
                type: 'text',
                content: 'PLASMA',
                font_info: {
                  italics: true,
                  IsBold: true,
                  font_size: -1,
                  font_style: '',
                  entity: [],
                  roi_id: {
                    para: 'bc4dc375-8a78-11ed-946e-005056ab6469',
                    childbox: '',
                    subtext: '',
                  },
                },
                level_1_CPT_section: 'Unmapped',
                file_section: 'Unmapped',
                file_section_num: '',
                file_section_level: 1,
                seq_num: 2,
                qc_change_type: '',
                line_id: 'bc5A80ba-8a78-11ed-8986-005056ab6469',
                aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
                synonyms_extracted_terms: '',
                semantic_extraction: '',
                section_locked: false,
                clinical_terms: {
                  CONFIDENTIAL: {
                    synonyms: 'value1, value2',
                  },
                },
              },
            ],
          },
        ],
        sections: [
          {
            section_level: '',
            CPT_section: 'Unmapped',
            type: 'text',
            content: 'CONFIDENTIAL',
            font_info: {
              IsBold: false,
              font_size: -1,
              font_style: '',
              entity: [],
              roi_id: {
                para: 'bc4dc375-8a78-11ed-946e-005056ab6469',
                childbox: '',
                subtext: '',
              },
            },
            level_1_CPT_section: 'Unmapped',
            file_section: 'Unmapped',
            file_section_num: '',
            file_section_level: 1,
            seq_num: 2,
            qc_change_type: '',
            line_id: 'bc5C80ba-8a78-11ed-8986-005056ab6469',
            aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
            synonyms_extracted_terms: '',
            semantic_extraction: '',
            section_locked: false,
            clinical_terms: {
              CONFIDENTIAL: {
                synonyms: 'value1, value2',
              },
            },
          },
          {
            section_level: '',
            CPT_section: 'Unmapped',
            type: 'text',
            content: 'PLASMA',
            font_info: {
              italics: true,
              IsBold: true,
              font_size: -1,
              font_style: '',
              entity: [],
              roi_id: {
                para: 'bc4dc375-8a78-11ed-946e-005056ab6469',
                childbox: '',
                subtext: '',
              },
            },
            level_1_CPT_section: 'Unmapped',
            file_section: 'Unmapped',
            file_section_num: '',
            file_section_level: 1,
            seq_num: 2,
            qc_change_type: '',
            line_id: 'bc5CA0ba-8a78-11ed-8986-005056ab6469',
            aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
            synonyms_extracted_terms: '',
            semantic_extraction: '',
            section_locked: false,
            clinical_terms: {
              CONFIDENTIAL: {
                synonyms: 'value1, value2',
              },
            },
          },
        ],
      },
    },
  },
};

export const preloadedDataForSchedule = {
  initialState: {
    user: {
      userDetail: {
        userId: 'u123456',
        username: 'test',
        email: 'test@iqvia.com',
        user_type: 'normal',
      },
    },
    protocol: {
      rightBladeValue: 'Schedule of Activities',
      activeTOC: ['bc4dc374-8a78-11ed-af64-005056ab6469'],
      protocolTocData: {
        success: true,
        data: [
          {
            doc_id: 'f2571c30-a39f-4d58-a092-09edaac5b814',
            group_type: 'DocumentLinks',
            link_id: 'bc4dc374-8a78-11ed-af64-005056ab6469',
            LinkLevel: 1,
            page: 0,
            sec_id: '',
            source_file_section: 'TITLE PAGE',
            LinkType: 'toc',
            line_id: 'f2571c30-a39f-4d58-a092-09edaac5b814',
            preferred_term: '',
            qc_change_type: '',
            sequence: 0,
            section_locked: false,
            audit_info: {
              last_reviewed_date: '17-04-2023',
              last_reviewed_by: '',
              total_no_review: 1,
            },
            linkandReference: 'test',
          },
        ],
      },
      summary: {
        loading: false,
        success: true,
        data: {
          id: 'f2571c30-a39f-4d58-a092-09edaac5b814',
          userId: '1150903',
          fileName: 'NCT03399370 (1).pdf',
          documentFilePath:
            '\\\\quintiles.net\\enterprise\\Services\\protdigtest\\pilot_iqvxml\\f2571c30-a39f-4d58-a092-09edaac5b814\\NCT03399370 (1).pdf',
          protocol: 'K-877-3.01CH',
          projectId: '',
          sponsor: null,
          indication: null,
          moleculeDevice: null,
          amendment: 'Y',
          isProcessing: false,
          percentComplete: '100',
          compareStatus: null,
          iqvXmlPathProc: null,
          iqvXmlPathComp: null,
          shortTitle: '',
          versionNumber: '01',
          documentStatus: 'draft',
          draftVersion: null,
          errorCode: null,
          errorReason: null,
          status: 'PROCESS_COMPLETED',
          qcStatus: 'QC_NOT_STARTED',
          phase: 'III',
          digitizedConfidenceInterval: null,
          completenessOfDigitization: null,
          protocolTitle:
            'Title of Study : A placebo-controlled, double-blind, randomized trial to evaluate the effect of 300 mg of inclisiran sodium given as subcutaneous injections in subjects with atherosclerotic cardiovascular disease (ASCVD) and elevated low-density lipoprotein cholesterol (LDL-C) Title of Study : A placebo-controlled, double-blind, randomized trial to evaluate the effect of 300 mg of inclisiran sodium given as subcutaneous injections in subjects with atherosclerotic cardiovascular disease (ASCVD) and elevated low-density lipoprotein cholesterol (LDL-C)',
          studyStatus: null,
          sourceSystem: null,
          environment: null,
          uploadDate: '2023-04-17T10:06:27.899757',
          timeCreated: '2023-04-17T10:06:27.899757',
          lastUpdated: '2023-04-17T10:06:27.899757',
          userCreated: null,
          userUpdated: null,
          approvalDate: null,
          isActive: true,
          nctId: null,
          amendmentNumber: null,
          redactProfile: 'profile_1',
          userUploadedFlag: false,
          userPrimaryRoleFlag: false,
          userFollowingFlag: false,
          wfData: [
            {
              id: 'f2571c30-a39f-4d58-a092-09edaac5b814',
              wfId: 'f2571c30-a39f-4d58-a092-09edaac5b814',
              wfStatus: 'COMPLETED',
              wfAllServices: [
                'triage',
                'digitizer1',
                'digitizer2',
                'extraction',
                'digitizer2_omopgenerate',
                'i2e_omop_update',
                'digitizer2_omopupdate',
                'digitizer2_compare',
                'meta_tagging',
                'meta_extraction',
                'analyzer',
                'es_ingestion',
                'email_notification',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
              ],
              wfName: 'full_flow',
              wfRunningServices: [],
              wfErrorMessageDetails: '',
              wfFinishedServices: [
                'triage',
                'digitizer1',
                'digitizer2',
                'extraction',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'i2e_omop_update',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_omopupdate',
                'es_ingestion',
                'meta_tagging',
                'meta_extraction',
                'email_notification',
              ],
              wfPercentComplete: 100,
              timeCreated: '17-Apr-2023',
            },
          ],
        },
      },
      sectionIndex: 0,
      TOCActiveAccordion: [true, false],
      sectionDetails: {
        protocol: '15-07',
        sectionResponse: {
          success: true,
        },
        data: [
          {
            linkId: 'bc4dc374-8a78-11ed-af64-005056ab6469',
            data: [
              {
                section_level: '',
                CPT_section: 'Unmapped',
                type: 'text',
                content: 'CONFIDENTIAL',
                link_and_reference: { 0: 'source_text' },
                font_info: {
                  IsBold: false,
                  font_size: -1,
                  font_style: '',
                  entity: [],
                  roi_id: {
                    para: 'bc5080ba-8a78-11ed-8986-005056ab6469',
                    childbox: '',
                    subtext: '',
                  },
                },
                level_1_CPT_section: 'Unmapped',
                file_section: 'Unmapped',
                file_section_num: '',
                file_section_level: 1,
                seq_num: 2,
                qc_change_type: '',
                line_id: 'bc5080ba-8a78-11ed-8986-005056ab6469',
                aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
                synonyms_extracted_terms: '',
                semantic_extraction: '',
                section_locked: false,
                clinical_terms: {
                  CONFIDENTIAL: {
                    synonyms: 'value1, value2',
                  },
                },
              },
              {
                section_level: '',
                CPT_section: 'Unmapped',
                type: 'text',
                content: 'PLASMA',
                link_and_reference: { 0: 'source_text' },
                font_info: {
                  italics: true,
                  IsBold: true,
                  font_size: -1,
                  font_style: '',
                  entity: [],
                  roi_id: {
                    para: 'bc5080ba-8a78-11ed-8986-005056ab6469',
                    childbox: '',
                    subtext: '',
                  },
                },
                level_1_CPT_section: 'Unmapped',
                file_section: 'Unmapped',
                file_section_num: '',
                file_section_level: 1,
                seq_num: 2,
                qc_change_type: '',
                line_id: 'bc5080ba-8a78-11ed-8986-005056ab6469',
                aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
                synonyms_extracted_terms: '',
                semantic_extraction: '',
                section_locked: false,
                clinical_terms: {
                  CONFIDENTIAL: {
                    synonyms: 'value1, value2',
                  },
                },
              },
            ],
          },
          {
            linkId: 'bc4dc375-8a78-11ed-946e-005056ab6469',
            data: [
              {
                section_level: '',
                CPT_section: 'Unmapped',
                type: 'text',
                content: 'PLASMA',
                font_info: {
                  italics: true,
                  IsBold: true,
                  font_size: -1,
                  font_style: '',
                  entity: [],
                  roi_id: {
                    para: 'bc4dc375-8a78-11ed-946e-005056ab6469',
                    childbox: '',
                    subtext: '',
                  },
                },
                level_1_CPT_section: 'Unmapped',
                file_section: 'Unmapped',
                file_section_num: '',
                file_section_level: 1,
                seq_num: 2,
                qc_change_type: '',
                line_id: 'bc5A80ba-8a78-11ed-8986-005056ab6469',
                aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
                synonyms_extracted_terms: '',
                semantic_extraction: '',
                section_locked: false,
                clinical_terms: {
                  CONFIDENTIAL: {
                    synonyms: 'value1, value2',
                  },
                },
              },
            ],
          },
        ],
        sections: [
          {
            section_level: '',
            CPT_section: 'Unmapped',
            type: 'text',
            content: 'CONFIDENTIAL',
            font_info: {
              IsBold: false,
              font_size: -1,
              font_style: '',
              entity: [],
              roi_id: {
                para: 'bc4dc375-8a78-11ed-946e-005056ab6469',
                childbox: '',
                subtext: '',
              },
            },
            level_1_CPT_section: 'Unmapped',
            file_section: 'Unmapped',
            file_section_num: '',
            file_section_level: 1,
            seq_num: 2,
            qc_change_type: '',
            line_id: 'bc5C80ba-8a78-11ed-8986-005056ab6469',
            aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
            synonyms_extracted_terms: '',
            semantic_extraction: '',
            section_locked: false,
            clinical_terms: {
              CONFIDENTIAL: {
                synonyms: 'value1, value2',
              },
            },
          },
          {
            section_level: '',
            CPT_section: 'Unmapped',
            type: 'text',
            content: 'PLASMA',
            font_info: {
              italics: true,
              IsBold: true,
              font_size: -1,
              font_style: '',
              entity: [],
              roi_id: {
                para: 'bc4dc375-8a78-11ed-946e-005056ab6469',
                childbox: '',
                subtext: '',
              },
            },
            level_1_CPT_section: 'Unmapped',
            file_section: 'Unmapped',
            file_section_num: '',
            file_section_level: 1,
            seq_num: 2,
            qc_change_type: '',
            line_id: 'bc5CA0ba-8a78-11ed-8986-005056ab6469',
            aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
            synonyms_extracted_terms: '',
            semantic_extraction: '',
            section_locked: false,
            clinical_terms: {
              CONFIDENTIAL: {
                synonyms: 'value1, value2',
              },
            },
          },
        ],
      },
    },
  },
};

export const preloadedDataForDipaView = {
  initialState: {
    user: {
      userDetail: {
        userId: 'u123456',
        username: 'test',
        email: 'test@iqvia.com',
        user_type: 'normal',
      },
    },
    protocol: {
      rightBladeValue: 'Derived Counts',
      activeTOC: ['bc4dc374-8a78-11ed-af64-005056ab6469'],
      dipaViewData: {
        loading: false,
      },
      protocolTocData: {
        success: true,
        data: [
          {
            doc_id: 'f2571c30-a39f-4d58-a092-09edaac5b814',
            group_type: 'DocumentLinks',
            link_id: 'bc4dc374-8a78-11ed-af64-005056ab6469',
            LinkLevel: 1,
            page: 0,
            sec_id: '',
            source_file_section: 'TITLE PAGE',
            LinkType: 'toc',
            line_id: 'f2571c30-a39f-4d58-a092-09edaac5b814',
            preferred_term: '',
            qc_change_type: '',
            sequence: 0,
            section_locked: false,
            audit_info: {
              last_reviewed_date: '17-04-2023',
              last_reviewed_by: '',
              total_no_review: 1,
            },
            linkandReference: 'test',
          },
        ],
      },
      summary: {
        loading: false,
        success: true,
        data: {
          id: 'f2571c30-a39f-4d58-a092-09edaac5b814',
          userId: '1150903',
          fileName: 'NCT03399370 (1).pdf',
          documentFilePath:
            '\\\\quintiles.net\\enterprise\\Services\\protdigtest\\pilot_iqvxml\\f2571c30-a39f-4d58-a092-09edaac5b814\\NCT03399370 (1).pdf',
          protocol: 'K-877-3.01CH',
          projectId: '',
          sponsor: null,
          indication: null,
          moleculeDevice: null,
          amendment: 'Y',
          isProcessing: false,
          percentComplete: '100',
          compareStatus: null,
          iqvXmlPathProc: null,
          iqvXmlPathComp: null,
          shortTitle: '',
          versionNumber: '01',
          documentStatus: 'draft',
          draftVersion: null,
          errorCode: null,
          errorReason: null,
          status: 'PROCESS_COMPLETED',
          qcStatus: 'QC_NOT_STARTED',
          phase: 'III',
          digitizedConfidenceInterval: null,
          completenessOfDigitization: null,
          protocolTitle:
            'Title of Study : A placebo-controlled, double-blind, randomized trial to evaluate the effect of 300 mg of inclisiran sodium given as subcutaneous injections in subjects with atherosclerotic cardiovascular disease (ASCVD) and elevated low-density lipoprotein cholesterol (LDL-C) Title of Study : A placebo-controlled, double-blind, randomized trial to evaluate the effect of 300 mg of inclisiran sodium given as subcutaneous injections in subjects with atherosclerotic cardiovascular disease (ASCVD) and elevated low-density lipoprotein cholesterol (LDL-C)',
          studyStatus: null,
          sourceSystem: null,
          environment: null,
          uploadDate: '2023-04-17T10:06:27.899757',
          timeCreated: '2023-04-17T10:06:27.899757',
          lastUpdated: '2023-04-17T10:06:27.899757',
          userCreated: null,
          userUpdated: null,
          approvalDate: null,
          isActive: true,
          nctId: null,
          amendmentNumber: null,
          redactProfile: 'profile_1',
          userUploadedFlag: false,
          userPrimaryRoleFlag: false,
          userFollowingFlag: false,
          wfData: [
            {
              id: 'f2571c30-a39f-4d58-a092-09edaac5b814',
              wfId: 'f2571c30-a39f-4d58-a092-09edaac5b814',
              wfStatus: 'COMPLETED',
              wfAllServices: [
                'triage',
                'digitizer1',
                'digitizer2',
                'extraction',
                'digitizer2_omopgenerate',
                'i2e_omop_update',
                'digitizer2_omopupdate',
                'digitizer2_compare',
                'meta_tagging',
                'meta_extraction',
                'analyzer',
                'es_ingestion',
                'email_notification',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
              ],
              wfName: 'full_flow',
              wfRunningServices: [],
              wfErrorMessageDetails: '',
              wfFinishedServices: [
                'triage',
                'digitizer1',
                'digitizer2',
                'extraction',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'i2e_omop_update',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_omopupdate',
                'es_ingestion',
                'meta_tagging',
                'meta_extraction',
                'email_notification',
              ],
              wfPercentComplete: 100,
              timeCreated: '17-Apr-2023',
            },
          ],
        },
      },
      sectionIndex: 0,
      TOCActiveAccordion: [true, false],
      sectionDetails: {
        protocol: '15-07',
        sectionResponse: {
          success: true,
        },
        data: [
          {
            linkId: 'bc4dc374-8a78-11ed-af64-005056ab6469',
            data: [
              {
                section_level: '',
                CPT_section: 'Unmapped',
                type: 'text',
                content: 'CONFIDENTIAL',
                link_and_reference: { 0: 'source_text' },
                font_info: {
                  IsBold: false,
                  font_size: -1,
                  font_style: '',
                  entity: [],
                  roi_id: {
                    para: 'bc5080ba-8a78-11ed-8986-005056ab6469',
                    childbox: '',
                    subtext: '',
                  },
                },
                level_1_CPT_section: 'Unmapped',
                file_section: 'Unmapped',
                file_section_num: '',
                file_section_level: 1,
                seq_num: 2,
                qc_change_type: '',
                line_id: 'bc5080ba-8a78-11ed-8986-005056ab6469',
                aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
                synonyms_extracted_terms: '',
                semantic_extraction: '',
                section_locked: false,
                clinical_terms: {
                  CONFIDENTIAL: {
                    synonyms: 'value1, value2',
                  },
                },
              },
              {
                section_level: '',
                CPT_section: 'Unmapped',
                type: 'text',
                content: 'PLASMA',
                link_and_reference: { 0: 'source_text' },
                font_info: {
                  italics: true,
                  IsBold: true,
                  font_size: -1,
                  font_style: '',
                  entity: [],
                  roi_id: {
                    para: 'bc5080ba-8a78-11ed-8986-005056ab6469',
                    childbox: '',
                    subtext: '',
                  },
                },
                level_1_CPT_section: 'Unmapped',
                file_section: 'Unmapped',
                file_section_num: '',
                file_section_level: 1,
                seq_num: 2,
                qc_change_type: '',
                line_id: 'bc5080ba-8a78-11ed-8986-005056ab6469',
                aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
                synonyms_extracted_terms: '',
                semantic_extraction: '',
                section_locked: false,
                clinical_terms: {
                  CONFIDENTIAL: {
                    synonyms: 'value1, value2',
                  },
                },
              },
            ],
          },
          {
            linkId: 'bc4dc375-8a78-11ed-946e-005056ab6469',
            data: [
              {
                section_level: '',
                CPT_section: 'Unmapped',
                type: 'text',
                content: 'PLASMA',
                font_info: {
                  italics: true,
                  IsBold: true,
                  font_size: -1,
                  font_style: '',
                  entity: [],
                  roi_id: {
                    para: 'bc4dc375-8a78-11ed-946e-005056ab6469',
                    childbox: '',
                    subtext: '',
                  },
                },
                level_1_CPT_section: 'Unmapped',
                file_section: 'Unmapped',
                file_section_num: '',
                file_section_level: 1,
                seq_num: 2,
                qc_change_type: '',
                line_id: 'bc5A80ba-8a78-11ed-8986-005056ab6469',
                aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
                synonyms_extracted_terms: '',
                semantic_extraction: '',
                section_locked: false,
                clinical_terms: {
                  CONFIDENTIAL: {
                    synonyms: 'value1, value2',
                  },
                },
              },
            ],
          },
        ],
        sections: [
          {
            section_level: '',
            CPT_section: 'Unmapped',
            type: 'text',
            content: 'CONFIDENTIAL',
            font_info: {
              IsBold: false,
              font_size: -1,
              font_style: '',
              entity: [],
              roi_id: {
                para: 'bc4dc375-8a78-11ed-946e-005056ab6469',
                childbox: '',
                subtext: '',
              },
            },
            level_1_CPT_section: 'Unmapped',
            file_section: 'Unmapped',
            file_section_num: '',
            file_section_level: 1,
            seq_num: 2,
            qc_change_type: '',
            line_id: 'bc5C80ba-8a78-11ed-8986-005056ab6469',
            aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
            synonyms_extracted_terms: '',
            semantic_extraction: '',
            section_locked: false,
            clinical_terms: {
              CONFIDENTIAL: {
                synonyms: 'value1, value2',
              },
            },
          },
          {
            section_level: '',
            CPT_section: 'Unmapped',
            type: 'text',
            content: 'PLASMA',
            font_info: {
              italics: true,
              IsBold: true,
              font_size: -1,
              font_style: '',
              entity: [],
              roi_id: {
                para: 'bc4dc375-8a78-11ed-946e-005056ab6469',
                childbox: '',
                subtext: '',
              },
            },
            level_1_CPT_section: 'Unmapped',
            file_section: 'Unmapped',
            file_section_num: '',
            file_section_level: 1,
            seq_num: 2,
            qc_change_type: '',
            line_id: 'bc5CA0ba-8a78-11ed-8986-005056ab6469',
            aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
            synonyms_extracted_terms: '',
            semantic_extraction: '',
            section_locked: false,
            clinical_terms: {
              CONFIDENTIAL: {
                synonyms: 'value1, value2',
              },
            },
          },
        ],
      },
    },
  },
};

export const mockDataForDiscard = {
  initialState: {
    protocol: {
      discardValue: {
        bladeRight: {
          name: 'clinical Terms',
        },
        isDiscarded: true,
        isEdited: true,
      },
      isSaveEnabled: true,
      sectionIndex: 0,
      sectionLockDetails: {
        section_lock: true,
      },
      TOCActiveAccordion: [true, false],
      activeTOC: ['bc4dc374-8a78-11ed-af64-005056ab646'],
      sectionDetails: {
        protocol: '15-07',
        sectionResponse: {
          success: true,
        },
        data: [
          {
            linkId: 'bc4dc374-8a78-11ed-af64-005056ab6469',
            data: [
              {
                section_level: '',
                CPT_section: 'Unmapped',
                type: 'text',
                content: 'CONFIDENTIAL',
                link_and_reference: { 0: 'source_text' },
                font_info: {
                  IsBold: false,
                  font_size: -1,
                  font_style: '',
                  entity: [],
                  roi_id: {
                    para: 'bc5080ba-8a78-11ed-8986-005056ab6469',
                    childbox: '',
                    subtext: '',
                  },
                },
                level_1_CPT_section: 'Unmapped',
                file_section: 'Unmapped',
                file_section_num: '',
                file_section_level: 1,
                seq_num: 2,
                qc_change_type: '',
                line_id: 'bc5080ba-8a78-11ed-8986-005056ab6469',
                aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
                synonyms_extracted_terms: '',
                semantic_extraction: '',
                section_locked: false,
                clinical_terms: {
                  CONFIDENTIAL: {
                    synonyms: 'value1, value2',
                  },
                },
              },
              {
                section_level: '',
                CPT_section: 'Unmapped',
                type: 'text',
                content: 'PLASMA',
                link_and_reference: { 0: 'source_text' },
                font_info: {
                  italics: true,
                  IsBold: true,
                  font_size: -1,
                  font_style: '',
                  entity: [],
                  roi_id: {
                    para: 'bc5080ba-8a78-11ed-8986-005056ab6469',
                    childbox: '',
                    subtext: '',
                  },
                },
                level_1_CPT_section: 'Unmapped',
                file_section: 'Unmapped',
                file_section_num: '',
                file_section_level: 1,
                seq_num: 2,
                qc_change_type: '',
                line_id: 'bc5080ba-8a78-11ed-8986-005056ab6469',
                aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
                synonyms_extracted_terms: '',
                semantic_extraction: '',
                section_locked: false,
                clinical_terms: {
                  CONFIDENTIAL: {
                    synonyms: 'value1, value2',
                  },
                },
              },
            ],
          },
        ],
        sections: [
          {
            section_level: '',
            CPT_section: 'Unmapped',
            type: 'text',
            content: 'CONFIDENTIAL',
            font_info: {
              IsBold: false,
              font_size: -1,
              font_style: '',
              entity: [],
              roi_id: {
                para: 'bc4dc375-8a78-11ed-946e-005056ab6469',
                childbox: '',
                subtext: '',
              },
            },
            level_1_CPT_section: 'Unmapped',
            file_section: 'Unmapped',
            file_section_num: '',
            file_section_level: 1,
            seq_num: 2,
            qc_change_type: '',
            line_id: 'bc5C80ba-8a78-11ed-8986-005056ab6469',
            aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
            synonyms_extracted_terms: '',
            semantic_extraction: '',
            section_locked: false,
            clinical_terms: {
              CONFIDENTIAL: {
                synonyms: 'value1, value2',
              },
            },
          },
          {
            section_level: '',
            CPT_section: 'Unmapped',
            type: 'text',
            content: 'PLASMA',
            font_info: {
              italics: true,
              IsBold: true,
              font_size: -1,
              font_style: '',
              entity: [],
              roi_id: {
                para: 'bc4dc375-8a78-11ed-946e-005056ab6469',
                childbox: '',
                subtext: '',
              },
            },
            level_1_CPT_section: 'Unmapped',
            file_section: 'Unmapped',
            file_section_num: '',
            file_section_level: 1,
            seq_num: 2,
            qc_change_type: '',
            line_id: 'bc5CA0ba-8a78-11ed-8986-005056ab6469',
            aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
            synonyms_extracted_terms: '',
            semantic_extraction: '',
            section_locked: false,
            clinical_terms: {
              CONFIDENTIAL: {
                synonyms: 'value1, value2',
              },
            },
          },
        ],
      },
    },
  },
};

export const mockDataForLockDetails = {
  initialState: {
    protocol: {
      discardValue: true,
      isSaveEnabled: false,
      sectionIndex: 0,
      sectionLockDetails: {
        section_lock: true,
      },
      TOCActiveAccordion: [true, false],
      activeTOC: ['bc4dc374-8a78-11ed-af64-005056ab646'],
      sectionDetails: {
        protocol: '15-07',
        sectionResponse: {
          success: true,
        },
        data: [
          {
            linkId: 'bc4dc374-8a78-11ed-af64-005056ab6469',
            data: [
              {
                section_level: '',
                CPT_section: 'Unmapped',
                type: 'text',
                content: 'CONFIDENTIAL',
                link_and_reference: { 0: 'source_text' },
                font_info: {
                  IsBold: false,
                  font_size: -1,
                  font_style: '',
                  entity: [],
                  roi_id: {
                    para: 'bc5080ba-8a78-11ed-8986-005056ab6469',
                    childbox: '',
                    subtext: '',
                  },
                },
                level_1_CPT_section: 'Unmapped',
                file_section: 'Unmapped',
                file_section_num: '',
                file_section_level: 1,
                seq_num: 2,
                qc_change_type: '',
                line_id: 'bc5080ba-8a78-11ed-8986-005056ab6469',
                aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
                synonyms_extracted_terms: '',
                semantic_extraction: '',
                section_locked: false,
                clinical_terms: {
                  CONFIDENTIAL: {
                    synonyms: 'value1, value2',
                  },
                },
              },
              {
                section_level: '',
                CPT_section: 'Unmapped',
                type: 'text',
                content: 'PLASMA',
                link_and_reference: { 0: 'source_text' },
                font_info: {
                  italics: true,
                  IsBold: true,
                  font_size: -1,
                  font_style: '',
                  entity: [],
                  roi_id: {
                    para: 'bc5080ba-8a78-11ed-8986-005056ab6469',
                    childbox: '',
                    subtext: '',
                  },
                },
                level_1_CPT_section: 'Unmapped',
                file_section: 'Unmapped',
                file_section_num: '',
                file_section_level: 1,
                seq_num: 2,
                qc_change_type: '',
                line_id: 'bc5080ba-8a78-11ed-8986-005056ab6469',
                aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
                synonyms_extracted_terms: '',
                semantic_extraction: '',
                section_locked: false,
                clinical_terms: {
                  CONFIDENTIAL: {
                    synonyms: 'value1, value2',
                  },
                },
              },
            ],
          },
        ],
        sections: [
          {
            section_level: '',
            CPT_section: 'Unmapped',
            type: 'text',
            content: 'CONFIDENTIAL',
            font_info: {
              IsBold: false,
              font_size: -1,
              font_style: '',
              entity: [],
              roi_id: {
                para: 'bc4dc375-8a78-11ed-946e-005056ab6469',
                childbox: '',
                subtext: '',
              },
            },
            level_1_CPT_section: 'Unmapped',
            file_section: 'Unmapped',
            file_section_num: '',
            file_section_level: 1,
            seq_num: 2,
            qc_change_type: '',
            line_id: 'bc5C80ba-8a78-11ed-8986-005056ab6469',
            aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
            synonyms_extracted_terms: '',
            semantic_extraction: '',
            section_locked: false,
            clinical_terms: {
              CONFIDENTIAL: {
                synonyms: 'value1, value2',
              },
            },
          },
          {
            section_level: '',
            CPT_section: 'Unmapped',
            type: 'text',
            content: 'PLASMA',
            font_info: {
              italics: true,
              IsBold: true,
              font_size: -1,
              font_style: '',
              entity: [],
              roi_id: {
                para: 'bc4dc375-8a78-11ed-946e-005056ab6469',
                childbox: '',
                subtext: '',
              },
            },
            level_1_CPT_section: 'Unmapped',
            file_section: 'Unmapped',
            file_section_num: '',
            file_section_level: 1,
            seq_num: 2,
            qc_change_type: '',
            line_id: 'bc5CA0ba-8a78-11ed-8986-005056ab6469',
            aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
            synonyms_extracted_terms: '',
            semantic_extraction: '',
            section_locked: false,
            clinical_terms: {
              CONFIDENTIAL: {
                synonyms: 'value1, value2',
              },
            },
          },
        ],
      },
    },
  },
};

export const mockStateDataForEmptyLockDetails = {
  initialState: {
    protocol: {
      discardValue: true,
      isSaveEnabled: false,
      sectionIndex: 0,
      sectionLockDetails: {},
      TOCActiveAccordion: [true, false],
      activeTOC: ['bc4dc374-8a78-11ed-af64-005056ab646'],
      sectionDetails: {
        protocol: '15-07',
        sectionResponse: {
          success: true,
        },
        data: [
          {
            linkId: 'bc4dc374-8a78-11ed-af64-005056ab64',
            data: [
              {
                section_level: '',
                CPT_section: 'Unmapped',
                type: 'text',
                content: 'CONFIDENTIAL',
                link_and_reference: { 0: 'source_text' },
                font_info: {
                  IsBold: false,
                  font_size: -1,
                  font_style: '',
                  entity: [],
                  roi_id: {
                    para: 'bc5080ba-8a78-11ed-8986-005056ab6469',
                    childbox: '',
                    subtext: '',
                  },
                },
                level_1_CPT_section: 'Unmapped',
                file_section: 'Unmapped',
                file_section_num: '',
                file_section_level: 1,
                seq_num: 2,
                qc_change_type: '',
                line_id: 'bc5080ba-8a78-11ed-8986-005056ab6469',
                aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
                synonyms_extracted_terms: '',
                semantic_extraction: '',
                section_locked: false,
                clinical_terms: {
                  CONFIDENTIAL: {
                    synonyms: 'value1, value2',
                  },
                },
              },
              {
                section_level: '',
                CPT_section: 'Unmapped',
                type: 'text',
                content: 'PLASMA',
                link_and_reference: { 0: 'source_text' },
                font_info: {
                  italics: true,
                  IsBold: true,
                  font_size: -1,
                  font_style: '',
                  entity: [],
                  roi_id: {
                    para: 'bc5080ba-8a78-11ed-8986-005056ab6469',
                    childbox: '',
                    subtext: '',
                  },
                },
                level_1_CPT_section: 'Unmapped',
                file_section: 'Unmapped',
                file_section_num: '',
                file_section_level: 1,
                seq_num: 2,
                qc_change_type: '',
                line_id: 'bc5080ba-8a78-11ed-8986-005056ab6469',
                aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
                synonyms_extracted_terms: '',
                semantic_extraction: '',
                section_locked: false,
                clinical_terms: {
                  CONFIDENTIAL: {
                    synonyms: 'value1, value2',
                  },
                },
              },
            ],
          },
        ],
        sections: [
          {
            section_level: '',
            CPT_section: 'Unmapped',
            type: 'text',
            content: 'CONFIDENTIAL',
            font_info: {
              IsBold: false,
              font_size: -1,
              font_style: '',
              entity: [],
              roi_id: {
                para: 'bc4dc375-8a78-11ed-946e-005056ab6469',
                childbox: '',
                subtext: '',
              },
            },
            level_1_CPT_section: 'Unmapped',
            file_section: 'Unmapped',
            file_section_num: '',
            file_section_level: 1,
            seq_num: 2,
            qc_change_type: '',
            line_id: 'bc5C80ba-8a78-11ed-8986-005056ab6469',
            aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
            synonyms_extracted_terms: '',
            semantic_extraction: '',
            section_locked: false,
            clinical_terms: {
              CONFIDENTIAL: {
                synonyms: 'value1, value2',
              },
            },
          },
          {
            section_level: '',
            CPT_section: 'Unmapped',
            type: 'text',
            content: 'PLASMA',
            font_info: {
              italics: true,
              IsBold: true,
              font_size: -1,
              font_style: '',
              entity: [],
              roi_id: {
                para: 'bc4dc375-8a78-11ed-946e-005056ab6469',
                childbox: '',
                subtext: '',
              },
            },
            level_1_CPT_section: 'Unmapped',
            file_section: 'Unmapped',
            file_section_num: '',
            file_section_level: 1,
            seq_num: 2,
            qc_change_type: '',
            line_id: 'bc5CA0ba-8a78-11ed-8986-005056ab6469',
            aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
            synonyms_extracted_terms: '',
            semantic_extraction: '',
            section_locked: false,
            clinical_terms: {
              CONFIDENTIAL: {
                synonyms: 'value1, value2',
              },
            },
          },
        ],
      },
    },
  },
};

export const headerListData = [
  {
    doc_id: 'f2571c30-a39f-4d58-a092-09edaac5b814',
    group_type: 'DocumentLinks',
    link_id: 'bc4dc374-8a78-11ed-af64-005056ab6469',
    LinkLevel: 1,
    page: 0,
    sec_id: '',
    source_file_section: 'TITLE PAGE',
    LinkType: 'toc',
    line_id: 'f2571c30-a39f-4d58-a092-09edaac5b814',
    preferred_term: '',
    qc_change_type: '',
    sequence: 0,
    section_locked: false,
    audit_info: {
      last_reviewed_date: '17-04-2023',
      last_reviewed_by: '',
      total_no_review: 1,
    },
    linkandReference: 'test',
  },
];

export const headerListWithoutLinkAndReference = [
  {
    doc_id: 'f2571c30-a39f-4d58-a092-09edaac5b814',
    group_type: 'DocumentLinks',
    link_id: 'bc4dc374-8a78-11ed-af64-005056ab6469',
    LinkLevel: 1,
    page: 0,
    sec_id: '',
    source_file_section: 'TITLE PAGE',
    LinkType: 'toc',
    line_id: 'f2571c30-a39f-4d58-a092-09edaac5b814',
    preferred_term: '',
    qc_change_type: '',
    sequence: 0,
    section_locked: false,
    audit_info: {
      last_reviewed_date: '17-04-2023',
      last_reviewed_by: '',
      total_no_review: 1,
    },
  },
];

export const headerListDataForDiffLinkId = [
  {
    doc_id: 'f2571c30-a39f-4d58-a092-09edaac5b814',
    group_type: 'DocumentLinks',
    link_id: 'bc4dc37',
    LinkLevel: 1,
    page: 0,
    sec_id: '',
    source_file_section: 'TITLE PAGE',
    LinkType: 'toc',
    line_id: 'f2571c30-a39f-4d58-a092-09edaac5b814',
    preferred_term: '',
    qc_change_type: '',
    sequence: 0,
    section_locked: false,
    audit_info: {
      last_reviewed_date: '17-04-2023',
      last_reviewed_by: '',
      total_no_review: 1,
    },
    linkandReference: 'test',
  },
];
