export const associateData1 = [
  {
    id: "0bd85f42-fa69-42c1-ac4b-b1b6d3b25e14",
    userId: "1021402",
    fileName: "Acrobat Document.pdf",
    documentFilePath:
      "\\\\INKOCWL000200\\Users\\q1036048\\Desktop\\__pycache__\\PD\\pd-management\\0bd85f42-fa69-42c1-ac4b-b1b6d3b25e14\\Acrobat Document.pdf",
    protocol: "AB1",
    projectId: "123",
    sponsor: "Astellas Pharma Inc",
    indication: "ABCC6 deficiency",
    moleculeDevice: "DEV1",
    amendment: "N",
    isProcessing: true,
    percentComplete: "45",
    compareStatus: null,
    iqvXmlPathProc: null,
    iqvXmlPathComp: null,
    shortTitle: null,
    versionNumber: "1.1",
    documentStatus: "active",
    draftVersion: null,
    errorCode: null,
    errorReason: null,
    status: "I2E_OMOP_UPDATE_STARTED",
    phase: null,
    digitizedConfidenceInterval: null,
    completenessOfDigitization: null,
    protocolTitle: null,
    studyStatus: null,
    sourceSystem: null,
    environment: null,
    uploadDate: "2020-12-29T07:59:14.303000",
    timeCreated: "2020-12-29T07:59:14.303000",
    lastUpdated: "2020-12-29T08:00:13.663000",
    userCreated: null,
    userUpdated: null,
    approvalDate: null,
    isActive: false,
    nctId: null,
  },
  {
    id: "21bab274-1b66-4c14-b0a1-5487f111fc60",
    userId: "1234",
    fileName: "a",
    documentFilePath:
      "\\\\INKOCWL000200\\Users\\q1036048\\Desktop\\__pycache__\\PD\\pd-management\\21bab274-1b66-4c14-b0a1-5487f111fc60\\Acrobat Document.pdf",
    protocol: "AB1",
    projectId: "123",
    sponsor: "Astra",
    indication: "fever",
    moleculeDevice: "dev1",
    amendment: "N",
    isProcessing: true,
    percentComplete: "45",
    compareStatus: null,
    iqvXmlPathProc: null,
    iqvXmlPathComp: null,
    shortTitle: null,
    versionNumber: "1.1",
    documentStatus: "active",
    draftVersion: null,
    errorCode: null,
    errorReason: null,
    status: "I2E_OMOP_UPDATE_STARTED",
    phase: null,
    digitizedConfidenceInterval: null,
    completenessOfDigitization: null,
    protocolTitle: null,
    studyStatus: "a",
    sourceSystem: "a",
    environment: "a",
    uploadDate: "2020-12-29T04:53:30",
    timeCreated: "2020-12-29T04:53:30",
    lastUpdated: "2020-12-29T04:54:15.687000",
    userCreated: null,
    userUpdated: null,
    approvalDate: null,
    isActive: false,
    nctId: null,
  },
  {
    id: "26486da5-6226-46ec-b3a1-eb25b9ae0cc1",
    userId: "1234",
    fileName: "a",
    documentFilePath:
      "\\\\INKOCWL000200\\Users\\q1036048\\Desktop\\__pycache__\\PD\\pd-management\\26486da5-6226-46ec-b3a1-eb25b9ae0cc1\\Acrobat Document.pdf",
    protocol: "AB1",
    projectId: "123",
    sponsor: "Astra",
    indication: "fever",
    moleculeDevice: "dev1",
    amendment: "N",
    isProcessing: true,
    percentComplete: "0",
    compareStatus: null,
    iqvXmlPathProc: null,
    iqvXmlPathComp: null,
    shortTitle: null,
    versionNumber: "1.1",
    documentStatus: "active",
    draftVersion: null,
    errorCode: null,
    errorReason: null,
    status: "TRIAGE_STARTED",
    phase: null,
    digitizedConfidenceInterval: null,
    completenessOfDigitization: null,
    protocolTitle: null,
    studyStatus: "a",
    sourceSystem: "a",
    environment: "a",
    uploadDate: "2020-12-29T07:58:12.900000",
    timeCreated: "2020-12-29T07:58:12.900000",
    lastUpdated: "2020-12-29T07:58:12.900000",
    userCreated: null,
    userUpdated: null,
    approvalDate: null,
    isActive: false,
    nctId: null,
  },
  {
    id: "9a437d45-1c61-4e21-ba47-18d3234afbbe",
    userId: "1021402",
    fileName: "Acrobat Document.pdf",
    documentFilePath:
      "\\\\INKOCWL000200\\Users\\q1036048\\Desktop\\__pycache__\\PD\\pd-management\\9a437d45-1c61-4e21-ba47-18d3234afbbe\\Acrobat Document.pdf",
    protocol: "AB1",
    projectId: "123",
    sponsor: "NVT AG",
    indication: "ABCC6 deficiency",
    moleculeDevice: "dev1",
    amendment: "N",
    isProcessing: true,
    percentComplete: "45",
    compareStatus: null,
    iqvXmlPathProc: null,
    iqvXmlPathComp: null,
    shortTitle: null,
    versionNumber: "1.2",
    documentStatus: "active",
    draftVersion: null,
    errorCode: null,
    errorReason: null,
    status: "I2E_OMOP_UPDATE_STARTED",
    phase: null,
    digitizedConfidenceInterval: null,
    completenessOfDigitization: null,
    protocolTitle: null,
    studyStatus: null,
    sourceSystem: null,
    environment: null,
    uploadDate: "2020-12-29T08:01:19.177000",
    timeCreated: "2020-12-29T08:01:19.177000",
    lastUpdated: "2020-12-29T08:02:29.700000",
    userCreated: null,
    userUpdated: null,
    approvalDate: null,
    isActive: false,
    nctId: null,
  },
];

export const compare = {
  compareId: "767686990098",
  id1: "0bd85f42-fa69-42c1-ac4b-b1b6d3b25e14",
  protocolNumber: "AB1",
  projectId: "123",
  versionNumber: "1.1",
  amendmentNumber: "N",
  documentStatus: "active",
  id2: "9a437d45-1c61-4e21-ba47-18d3234afbbe",
  protocolNumber2: "AB1",
  projectId2: "123",
  versionNumber2: "1.2",
  amendmentNumber2: "N",
  documentStatus2: "active",
  environment: "",
  sourceSystem: "",
  userId: "1021421",
  requestType: "COMPARE_TOC",
  iqvdata: {
    index: [
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
    ],
    columns: [
      "seq_num",
      "section",
      "text_type",
      "diff_type",
      "base_text",
      "compare_text",
      "char_diff",
      "confidence_score",
    ],
    data: [
      [
        1,
        "Table of Contents",
        "header",
        0,
        "VERSION HISTORY",
        "VERSION HISTORY",
        [],
        1,
      ],
      [
        2,
        "Table of Contents",
        "text",
        0,
        "See Appendix A 5 for guidelines for the dissemination of study results.",
        "See Appendix A 5 for guidelines for the dissemination of study results.",
        [],
        1,
      ],
      [
        3,
        "Table of Contents",
        "text",
        2,
        "Lorem Ipsum is typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        [
          [15, 52],
          [367, 574],
        ],
        1,
      ],
      [
        4,
        "Table of Contents",
        "text",
        2,
        "approval protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        "Prospective approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        [
          [0, 11],
          [21, 23],
        ],
        1,
      ],
      [
        5,
        "Table of Contents",
        "text",
        2,
        "Prospective approval protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        "Prospective approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        [[21, 23]],
        1,
      ],
      [
        6,
        "Table of Contents",
        "header",
        0,
        "TABLE OF CONTENTS",
        "TABLE OF CONTENTS",
        [],
        1,
      ],
      [
        7,
        "Table of Contents",
        "text",
        2,
        "approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        "Prospective approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        [[0, 11]],
        1,
      ],
      [
        8,
        "Table of Contents",
        "text",
        1,
        "See Appendix A 5 for guidelines for the dissemination of study results.",
        "",
        [],
        1,
      ],
      [
        3,
        "Table of Contents",
        "header",
        2,
        "Introduction",
        "Introductions",
        [],
        1,
      ],
      [
        1,
        "Table of Contents",
        "text",
        0,
        "See Appendix A 5 for guidelines for the dissemination of study results.",
        "See Appendix A 5 for guidelines for the dissemination of study results.",
        [],
        1,
      ],
      [
        1,
        "Table of Contents",
        "text",
        2,
        "Lorem Ipsum is typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        [
          [15, 52],
          [367, 574],
        ],
        1,
      ],
      [
        1,
        "Table of Contents",
        "text",
        2,
        "approval protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        "Prospective approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        [
          [0, 11],
          [21, 23],
        ],
        1,
      ],
      [
        1,
        "Table of Contents",
        "text",
        2,
        "Prospective approval protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        "Prospective approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        [[21, 23]],
        1,
      ],
      [
        4,
        "Table of Contents",
        "header",
        0,
        "Background and rationale for conducting this study",
        "Background and rationale for conducting this study",
        [],
        1,
      ],
      [
        1,
        "Table of Contents",
        "text",
        0,
        "See Appendix A 5 for guidelines for the dissemination of study results.",
        "See Appendix A 5 for guidelines for the dissemination of study results.",
        [],
        1,
      ],
      [
        1,
        "Table of Contents",
        "text",
        2,
        "Lorem Ipsum is typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        [
          [15, 52],
          [367, 574],
        ],
        1,
      ],
      [
        1,
        "Table of Contents",
        "text",
        2,
        "approval protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        "Prospective approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        [
          [0, 11],
          [21, 23],
        ],
        1,
      ],
      [
        1,
        "Table of Contents",
        "text",
        2,
        "Prospective approval protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        "Prospective approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        [[21, 23]],
        1,
      ],
      [5, "Table of Contents", "header", 0, "Background", "Background", [], 1],
      [
        1,
        "Table of Contents",
        "text",
        3,
        "",
        "See Appendix A 5 for guidelines for the dissemination of study results.",
        [],
        1,
      ],
      [
        1,
        "Table of Contents",
        "text",
        2,
        "Lorem Ipsum is typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        [
          [15, 52],
          [367, 574],
        ],
        1,
      ],
      [
        1,
        "Table of Contents",
        "text",
        2,
        "approval protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        "Prospective approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        [
          [0, 11],
          [21, 23],
        ],
        1,
      ],
      [
        1,
        "Table of Contents",
        "text",
        2,
        "Prospective approval protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        "Prospective approval of protocol deviations to recruitment and enrolment criteria, also known as protocol waivers or exemptions, is not permitted.",
        [[21, 23]],
        1,
      ],
    ],
  },
  baseIqvXmlPath:
    "//quintiles.net/enterprise/Services/protdigtest/pilot_iqvxml/17d2a6ac-0826-4c81-9de5-b0f5b6bed4e7 Protocol-2015-10-15-VER-V1.0-000001.20201204103457.xml.zip",
  compareIqvXmlPath:
    "//ProtAmendquintiles.net/enterprise/Services/protdigtest/pilot_iqvxml/108-SSR-TEST/FIN_SE_D2_D1_AKB-6548-CI-0014 2016-03-17-VER-V2.0-000006.20201201082411.xml.zip",
  updatedIqvXmlPath:
    "//quintiles.net/enterprise/Services/protdigtest/pilot_iqvxml/17d2a6ac-0826-4c81-9de5 Protocol-2015-10-15-VER-V1.0-000001.20201204103457.xml.zip",
  similarityScore: 98,
};
