const fontInfo1 = {
  IsBold: false,
  font_size: -1,
  font_style: '',
  entity: [],
  roi_id: {
    para: 'bc5080ba-8a78-11ed-8986-005056ab6469',
    childbox: '',
    subtext: '',
  },
};

const remainingSection = {
  level_1_CPT_section: 'Unmapped',
  file_section: 'Unmapped',
  file_section_num: '',
  file_section_level: 1,
  seq_num: 2,
  qc_change_type: '',
  line_id: 'bc5C80ba-8a78-11ed-8986-005056ab6469',
  aidocid: '78808eb2-6b1b-445f-bc89-4560ca66dd1c',
  synonyms_extracted_terms: '',
  semantic_extraction: '',
  section_locked: false,
  clinical_terms: {
    CONFIDENTIAL: {
      synonyms: 'value1, value2',
    },
  },
};

const preloadedStateData = {
  initialState: {
    user: {
      userDetail: {
        userId: 'u123456',
        username: 'test',
        email: 'test@iqvia.com',
        user_type: 'normal',
      },
    },
    protocol: {
      rightBladeValue: 'Home',
      activeTOC: ['bc4dc374-8a78-11ed-af64-005056ab6469'],
      protocolTocData: {
        success: true,
        data: [
          {
            doc_id: 'f2571c30-a39f-4d58-a092-09edaac5b814',
            group_type: 'DocumentLinks',
            link_id: 'bc4dc374-8a78-11ed-af64-005056ab6469',
            LinkLevel: 1,
            page: 0,
            sec_id: '',
            source_file_section: 'TITLE PAGE',
            LinkType: 'toc',
            line_id: 'f2571c30-a39f-4d58-a092-09edaac5b814',
            preferred_term: '',
            qc_change_type: '',
            sequence: 0,
            section_locked: false,
            audit_info: {
              last_reviewed_date: '17-04-2023',
              last_reviewed_by: '',
              total_no_review: 1,
            },
            linkandReference: 'test',
          },
        ],
      },
      summary: {
        loading: false,
        success: true,
        isWorkflowDone: true,
        data: {
          id: 'f2571c30-a39f-4d58-a092-09edaac5b814',
          userId: '1150903',
          fileName: 'NCT03399370 (1).pdf',
          documentFilePath:
            '\\\\quintiles.net\\enterprise\\Services\\protdigtest\\pilot_iqvxml\\f2571c30-a39f-4d58-a092-09edaac5b814\\NCT03399370 (1).pdf',
          protocol: 'K-877-3.01CH',
          projectId: '',
          sponsor: null,
          indication: null,
          moleculeDevice: null,
          amendment: 'Y',
          isProcessing: false,
          percentComplete: '100',
          compareStatus: null,
          iqvXmlPathProc: null,
          iqvXmlPathComp: null,
          shortTitle: '',
          versionNumber: '01',
          documentStatus: 'draft',
          draftVersion: null,
          errorCode: null,
          errorReason: null,
          status: 'PROCESS_COMPLETED',
          qcStatus: 'QC_NOT_STARTED',
          phase: 'III',
          digitizedConfidenceInterval: null,
          completenessOfDigitization: null,
          protocolTitle:
            'Title of Study : A placebo-controlled, double-blind, randomized trial to evaluate the effect of 300 mg of inclisiran sodium given as subcutaneous injections in subjects with atherosclerotic cardiovascular disease (ASCVD) and elevated low-density lipoprotein cholesterol (LDL-C) Title of Study : A placebo-controlled, double-blind, randomized trial to evaluate the effect of 300 mg of inclisiran sodium given as subcutaneous injections in subjects with atherosclerotic cardiovascular disease (ASCVD) and elevated low-density lipoprotein cholesterol (LDL-C)',
          studyStatus: null,
          sourceSystem: null,
          environment: null,
          uploadDate: '2023-04-17T10:06:27.899757',
          timeCreated: '2023-04-17T10:06:27.899757',
          lastUpdated: '2023-04-17T10:06:27.899757',
          userCreated: null,
          userUpdated: null,
          approvalDate: null,
          isActive: true,
          nctId: null,
          amendmentNumber: null,
          redactProfile: 'profile_1',
          userUploadedFlag: false,
          userPrimaryRoleFlag: false,
          userFollowingFlag: false,
          wfData: [
            {
              id: 'f2571c30-a39f-4d58-a092-09edaac5b814',
              wfId: 'f2571c30-a39f-4d58-a092-09edaac5b814',
              wfStatus: 'COMPLETED',
              wfAllServices: [
                'triage',
                'digitizer1',
                'digitizer2',
                'extraction',
                'digitizer2_omopgenerate',
                'i2e_omop_update',
                'digitizer2_omopupdate',
                'digitizer2_compare',
                'meta_tagging',
                'meta_extraction',
                'analyzer',
                'es_ingestion',
                'email_notification',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
              ],
              wfName: 'full_flow',
              wfRunningServices: [],
              wfErrorMessageDetails: '',
              wfFinishedServices: [
                'triage',
                'digitizer1',
                'digitizer2',
                'extraction',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'i2e_omop_update',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_compare',
                'digitizer2_omopupdate',
                'es_ingestion',
                'meta_tagging',
                'meta_extraction',
                'email_notification',
              ],
              wfPercentComplete: 100,
              timeCreated: '17-Apr-2023',
            },
          ],
        },
      },
      sectionIndex: 0,
      TOCActiveAccordion: [true, false],
      sectionDetails: {
        protocol: '15-07',
        sectionResponse: {
          success: true,
        },
        data: [
          {
            linkId: 'bc4dc374-8a78-11ed-af64-005056ab6469',
            data: [
              {
                section_level: '',
                CPT_section: 'Unmapped',
                type: 'text',
                content: 'CONFIDENTIAL',
                link_and_reference: { 0: 'source_text' },
                font_info: fontInfo1,
                ...remainingSection,
              },
              {
                section_level: '',
                CPT_section: 'Unmapped',
                type: 'text',
                content: 'PLASMA',
                link_and_reference: { 0: 'source_text' },
                font_info: { ...fontInfo1, italics: true },
                ...remainingSection,
              },
            ],
          },
          {
            linkId: 'bc4dc375-8a78-11ed-946e-005056ab6469',
            data: [
              {
                section_level: '',
                CPT_section: 'Unmapped',
                type: 'text',
                content: 'PLASMA',
                font_info: { ...fontInfo1, italics: true },
                ...remainingSection,
              },
            ],
          },
        ],
        sections: [
          {
            section_level: '',
            CPT_section: 'Unmapped',
            type: 'text',
            content: 'CONFIDENTIAL',
            font_info: fontInfo1,
            ...remainingSection,
          },
          {
            section_level: '',
            CPT_section: 'Unmapped',
            type: 'text',
            content: 'PLASMA',
            font_info: { ...fontInfo1, italics: true },
            ...remainingSection,
          },
        ],
      },
    },
  },
};

export default preloadedStateData;
