const initialState = {
  protocol: {
    SOAData: {
      id: 'd4153421-2b47-4ec5-b21c-80d907d73227',
      soa_data: [
        {
          tableId: 'bb900b05-034c-4430-ad27-34a6039561b2',
          studyVisit: [
            {
              day_timepoint: [],
            },
            {
              week_timepoint: [],
            },
            {
              month_timepoint: [],
            },
            {
              year_timepoint: [],
            },
            {
              cycle_timepoint: [
                {
                  table_row_index: 0,
                  table_column_index: 6,
                  indicator_text: 'L6',
                  table_roi_id: 'bb900b05-034c-4430-ad27-34a6039561b2',
                },
                {
                  table_row_index: 0,
                  table_column_index: 12,
                  indicator_text: 'L12',
                  table_roi_id: 'bb900b05-034c-4430-ad27-34a6039561b2',
                },
                {
                  table_row_index: 0,
                  table_column_index: 2,
                  indicator_text: 'L2',
                  table_roi_id: 'bb900b05-034c-4430-ad27-34a6039561b2',
                },
                {
                  table_row_index: 0,
                  table_column_index: 4,
                  indicator_text: 'L4',
                  table_roi_id: 'bb900b05-034c-4430-ad27-34a6039561b2',
                },
                {
                  table_row_index: 0,
                  table_column_index: 8,
                  indicator_text: 'L8',
                  table_roi_id: 'bb900b05-034c-4430-ad27-34a6039561b2',
                },
                {
                  table_row_index: 0,
                  table_column_index: 10,
                  indicator_text: 'L10',
                  table_roi_id: 'bb900b05-034c-4430-ad27-34a6039561b2',
                },
                {
                  table_row_index: 0,
                  table_column_index: 1,
                  indicator_text: 'L1',
                  table_roi_id: 'bb900b05-034c-4430-ad27-34a6039561b2',
                },
              ],
            },
            {
              visit_timepoint: [
                {
                  table_row_index: 0,
                  table_column_index: 6,
                  indicator_text: 'Visit',
                  table_roi_id: 'bb900b05-034c-4430-ad27-34a6039561b2',
                },
                {
                  table_row_index: 0,
                  table_column_index: 12,
                  indicator_text: 'Not',
                  table_roi_id: 'bb900b05-034c-4430-ad27-34a6039561b2',
                },
              ],
            },
            {
              epoch_timepoint: [
                {
                  table_row_index: 0,
                  table_column_index: 6,
                  indicator_text: 'Follow-up',
                  table_roi_id: 'bb900b05-034c-4430-ad27-34a6039561b2',
                },
                {
                  table_row_index: 0,
                  table_column_index: 2,
                  indicator_text: 'Follow-up',
                  table_roi_id: 'bb900b05-034c-4430-ad27-34a6039561b2',
                },
                {
                  table_row_index: 0,
                  table_column_index: 4,
                  indicator_text: 'Follow-up',
                  table_roi_id: 'bb900b05-034c-4430-ad27-34a6039561b2',
                },
                {
                  table_row_index: 0,
                  table_column_index: 8,
                  indicator_text: 'Follow-up',
                  table_roi_id: 'bb900b05-034c-4430-ad27-34a6039561b2',
                },
                {
                  table_row_index: 0,
                  table_column_index: 1,
                  indicator_text: 'Follow-up',
                  table_roi_id: 'bb900b05-034c-4430-ad27-34a6039561b2',
                },
              ],
            },
            {
              window_timepoint: [],
            },
          ],
          studyProcedure: [
            {
              table_row_index: 0,
              table_column_index: 0,
              indicator_text: 'Study Procedures',
            },
            {
              table_row_index: 5,
              table_column_index: 0,
              indicator_text: 'Vital signs',
            },
            {
              table_row_index: 6,
              table_column_index: 0,
              indicator_text: 'Telephone consultation',
            },
            {
              table_row_index: 7,
              table_column_index: 0,
              indicator_text: 'Adverse events',
            },
            {
              table_row_index: 8,
              table_column_index: 0,
              indicator_text: 'Concomitant medications',
            },
            {
              table_row_index: 10,
              table_column_index: 0,
              indicator_text: 'Hematology',
            },
            {
              table_row_index: 11,
              table_column_index: 0,
              indicator_text: 'Comprehensive chemistry',
            },
            {
              table_row_index: 12,
              table_column_index: 0,
              indicator_text: 'Liver panel',
            },
            {
              table_row_index: 13,
              table_column_index: 0,
              indicator_text: 'Autoantibodies',
            },
            {
              table_row_index: 14,
              table_column_index: 0,
              indicator_text: 'Quantitative IgG',
            },
            {
              table_row_index: 15,
              table_column_index: 0,
              indicator_text:
                'Glomerular filtration rate (creatinine and height)',
            },
            {
              table_row_index: 16,
              table_column_index: 0,
              indicator_text: 'Hemoglobin A1C',
            },
            {
              table_row_index: 18,
              table_column_index: 0,
              indicator_text:
                'Whole blood quantitative PCR for CMV reactivation',
            },
            {
              table_row_index: 19,
              table_column_index: 0,
              indicator_text:
                'Whole blood quantitative PCR for EBV reactivation',
            },
            {
              table_row_index: 21,
              table_column_index: 0,
              indicator_text: 'Liver biopsies18, 19                  ',
            },
            {
              table_row_index: 23,
              table_column_index: 0,
              indicator_text: 'Whole blood flow cytometry panel staining',
            },
            {
              table_row_index: 24,
              table_column_index: 0,
              indicator_text: 'Frozen PBMC T-cell assays',
            },
            {
              table_row_index: 25,
              table_column_index: 0,
              indicator_text: 'Liver biopsy histology 2',
            },
            {
              table_row_index: 26,
              table_column_index: 0,
              indicator_text: 'Whole blood gene expression profiling',
            },
            {
              table_row_index: 27,
              table_column_index: 0,
              indicator_text: 'Liver biopsy RNA gene expression profiling 2',
            },
            {
              table_row_index: 28,
              table_column_index: 0,
              indicator_text: 'Serum secreted cytokines',
            },
            {
              table_row_index: 29,
              table_column_index: 0,
              indicator_text: 'Serum HLA alloantibodies',
            },
          ],
          normalized_SOA: [
            {
              id: '2aabd603-5452-4d95-9cce-98f029d01a82',
              epoch_timepoint: 'Follow-up',
              ProcessVersion: '15.15.8.0',
              table_sequence_index: -1,
              doc_id: 'd4153421-2b47-4ec5-b21c-80d907d73227',
              indicator_text: 'X',
              roi_id: 'eb0f9059-5a63-4763-851d-42461baf5d65',
              study_cohort: '',
              run_id: '',
              month_timepoint: '',
              table_row_index: 4,
              visit_timepoint: '',
              assessment: 'Physical examination',
              pname: 'NCT00320606.pdf',
              table_column_index: 6,
              week_timepoint: '',
              assessment_text: 'Physical examination',
              procedure: '',
              section: '',
              window_timepoint: '',
              cycle_timepoint: 'L6',
              procedure_text: '',
              table_link_text:
                'Appendix 3.  Schedule of Events: Low-intensity Follow-up',
              year_timepoint: '',
              day_timepoint: '',
              ProcessMachineName: 'CA2SPDML03Q',
              DocumentSequenceIndex: -1,
              dts: '20230303044213',
              table_roi_id: 'bb900b05-034c-4430-ad27-34a6039561b2',
              footnotes: [
                '2 Additional biopsies will be performed if necessary to rule out rejection.',
                '2 Additional biopsies will be performed if necessary to rule out rejection.',
                '1 Can be performed within 9 weeks before the liver biopsy visit.',
                '1 Can be performed within 9 weeks before the liver biopsy visit.',
                '2 LFTs must be performed upon diagnosis of allograft dysfunction or rejection and at the resolution of rejection (see sections 5.5.2 and 5.5.3.1).  Additional LFTs may be performed during rejection at the investigators discretion.',
                '4 Additional biopsies will be done to rule out rejection if necessary.',
                '4 Additional biopsies will be done to rule out rejection if necessary.',
                '5 Will be performed within 4 to 8 weeks after the last dose of immunosuppressant is taken.',
                '6 Will be performed only at visit 12 and not at visit 24.',
                '8 Please try to collect blood at assigned visit -2; if this is not possible,  collect at visit 1.  If not able to collect at visit 1,  please collect at visit 0.',
                '9 To be collected from living donor and nondonor parents after they have signed the informed consent; blood',
                '8 Please try to collect blood at assigned visit -2; if this is not possible,  collect at visit 1.  If not able to collect at visit 1,  please collect at visit 0.',
                '9 To be collected from living donor and nondonor parents after they have signed the informed consent; blood',
                '9 To be collected from living donor and nondonor parents after they have signed the informed consent; blood',
                '9 To be collected from living donor and nondonor parents after they have signed the informed consent; blood',
                '9 To be collected from living donor and nondonor parents after they have signed the informed consent; blood',
                '5 Will be performed within 4 to 8 weeks after the last dose of immunosuppressant is taken.',
                '6 Will be performed only at visit 12 and not at visit 24.',
                '8 Please try to collect blood at assigned visit -2; if this is not possible,  collect at visit 1.  If not able to collect at visit 1,  please collect at visit 0.',
                '5 Will be performed within 4 to 8 weeks after the last dose of immunosuppressant is taken.',
                '6 Will be performed only at visit 12 and not at visit 24.',
                '8 Please try to collect blood at assigned visit -2; if this is not possible,  collect at visit 1.  If not able to collect at visit 1,  please collect at visit 0.',
                '8 Please try to collect blood at assigned visit -2; if this is not possible,  collect at visit 1.  If not able to collect at visit 1,  please collect at visit 0.',
                '9 To be collected from living donor and nondonor parents after they have signed the informed consent; blood',
                '8 Please try to collect blood at assigned visit -2; if this is not possible,  collect at visit 1.  If not able to collect at visit 1,  please collect at visit 0.',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Liver biopsy will be performed as part of the E36 visit. Additional biopsies will be performed according to protocol guidelines or at the discretion of the site investigator.{0,0,0,0}',
                '2 Will be performed only at visit M1 and not at visit M13.',
                '2 Will be performed only at visit M1 and not at visit M13.',
                '2 Will be performed only at visit M1 and not at visit M13.',
                '2 Will be performed only at visit M1 and not at visit M13.',
                '2 Will be performed only at visit M1 and not at visit M13.',
                '3 Do not collect if last sample was collected less than 6 weeks before visit M1.',
                '2 Will be performed only at visit M1 and not at visit M13.',
                '2 Will be performed only at visit M1 and not at visit M13.',
                '4 Additional biopsies will be performed if necessary to rule out rejection.',
                '4 Additional biopsies will be performed if necessary to rule out rejection.',
              ],
              marked_record: {
                'Physical examination': ['Follow-up', 'L6'],
              },
            },
            {
              id: '6b3180fd-009c-40fe-9eea-2b96adad9d06',
              epoch_timepoint: '',
              ProcessVersion: '15.15.8.0',
              table_sequence_index: -1,
              doc_id: 'd4153421-2b47-4ec5-b21c-80d907d73227',
              indicator_text: 'X',
              roi_id: 'eb0f9059-5a63-4763-851d-42461baf5d65',
              study_cohort: '',
              run_id: '',
              month_timepoint: '',
              table_row_index: 4,
              visit_timepoint: '',
              assessment: 'Physical examination',
              pname: 'NCT00320606.pdf',
              table_column_index: 12,
              week_timepoint: '',
              assessment_text: 'Physical examination',
              procedure: '',
              section: '',
              window_timepoint: '',
              cycle_timepoint: 'L12',
              procedure_text: '',
              table_link_text:
                'Appendix 3.  Schedule of Events: Low-intensity Follow-up',
              year_timepoint: '',
              day_timepoint: '',
              ProcessMachineName: 'CA2SPDML03Q',
              DocumentSequenceIndex: -1,
              dts: '20230303044213',
              table_roi_id: 'bb900b05-034c-4430-ad27-34a6039561b2',
              footnotes: [
                '2 Additional biopsies will be performed if necessary to rule out rejection.',
                '2 Additional biopsies will be performed if necessary to rule out rejection.',
                '1 Can be performed within 9 weeks before the liver biopsy visit.',
                '1 Can be performed within 9 weeks before the liver biopsy visit.',
                '2 LFTs must be performed upon diagnosis of allograft dysfunction or rejection and at the resolution of rejection (see sections 5.5.2 and 5.5.3.1).  Additional LFTs may be performed during rejection at the investigators discretion.',
                '4 Additional biopsies will be done to rule out rejection if necessary.',
                '4 Additional biopsies will be done to rule out rejection if necessary.',
                '5 Will be performed within 4 to 8 weeks after the last dose of immunosuppressant is taken.',
                '6 Will be performed only at visit 12 and not at visit 24.',
                '8 Please try to collect blood at assigned visit -2; if this is not possible,  collect at visit 1.  If not able to collect at visit 1,  please collect at visit 0.',
                '9 To be collected from living donor and nondonor parents after they have signed the informed consent; blood',
                '8 Please try to collect blood at assigned visit -2; if this is not possible,  collect at visit 1.  If not able to collect at visit 1,  please collect at visit 0.',
                '9 To be collected from living donor and nondonor parents after they have signed the informed consent; blood',
                '9 To be collected from living donor and nondonor parents after they have signed the informed consent; blood',
                '9 To be collected from living donor and nondonor parents after they have signed the informed consent; blood',
                '9 To be collected from living donor and nondonor parents after they have signed the informed consent; blood',
                '5 Will be performed within 4 to 8 weeks after the last dose of immunosuppressant is taken.',
                '6 Will be performed only at visit 12 and not at visit 24.',
                '8 Please try to collect blood at assigned visit -2; if this is not possible,  collect at visit 1.  If not able to collect at visit 1,  please collect at visit 0.',
                '5 Will be performed within 4 to 8 weeks after the last dose of immunosuppressant is taken.',
                '6 Will be performed only at visit 12 and not at visit 24.',
                '8 Please try to collect blood at assigned visit -2; if this is not possible,  collect at visit 1.  If not able to collect at visit 1,  please collect at visit 0.',
                '8 Please try to collect blood at assigned visit -2; if this is not possible,  collect at visit 1.  If not able to collect at visit 1,  please collect at visit 0.',
                '9 To be collected from living donor and nondonor parents after they have signed the informed consent; blood',
                '8 Please try to collect blood at assigned visit -2; if this is not possible,  collect at visit 1.  If not able to collect at visit 1,  please collect at visit 0.',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Liver biopsy will be performed as part of the E36 visit. Additional biopsies will be performed according to protocol guidelines or at the discretion of the site investigator.{0,0,0,0}',
                '2 Will be performed only at visit M1 and not at visit M13.',
                '2 Will be performed only at visit M1 and not at visit M13.',
                '2 Will be performed only at visit M1 and not at visit M13.',
                '2 Will be performed only at visit M1 and not at visit M13.',
                '2 Will be performed only at visit M1 and not at visit M13.',
                '3 Do not collect if last sample was collected less than 6 weeks before visit M1.',
                '2 Will be performed only at visit M1 and not at visit M13.',
                '2 Will be performed only at visit M1 and not at visit M13.',
                '4 Additional biopsies will be performed if necessary to rule out rejection.',
                '4 Additional biopsies will be performed if necessary to rule out rejection.',
              ],
              marked_record: {
                'Physical examination': ['L12'],
              },
            },
          ],
        },
        {
          tableId: '77b727c9-1296-4915-9258-64ee45d2c8f6',
          studyVisit: [
            {
              day_timepoint: [],
            },
            {
              week_timepoint: [],
            },
            {
              month_timepoint: [],
            },
            {
              year_timepoint: [],
            },
            {
              cycle_timepoint: [
                {
                  table_row_index: 0,
                  table_column_index: 1,
                  indicator_text: ' 2',
                  table_roi_id: '77b727c9-1296-4915-9258-64ee45d2c8f6',
                },
                {
                  table_row_index: 0,
                  table_column_index: 2,
                  indicator_text: ' 1',
                  table_roi_id: '77b727c9-1296-4915-9258-64ee45d2c8f6',
                },
                {
                  table_row_index: 0,
                  table_column_index: 6,
                  indicator_text: '3',
                  table_roi_id: '77b727c9-1296-4915-9258-64ee45d2c8f6',
                },
                {
                  table_row_index: 0,
                  table_column_index: 9,
                  indicator_text: '6',
                  table_roi_id: '77b727c9-1296-4915-9258-64ee45d2c8f6',
                },
                {
                  table_row_index: 0,
                  table_column_index: 12,
                  indicator_text: '9',
                  table_roi_id: '77b727c9-1296-4915-9258-64ee45d2c8f6',
                },
                {
                  table_row_index: 0,
                  table_column_index: 15,
                  indicator_text: '12',
                  table_roi_id: '77b727c9-1296-4915-9258-64ee45d2c8f6',
                },
                {
                  table_row_index: 0,
                  table_column_index: 3,
                  indicator_text: '0',
                  table_roi_id: '77b727c9-1296-4915-9258-64ee45d2c8f6',
                },
                {
                  table_row_index: 0,
                  table_column_index: 4,
                  indicator_text: '1',
                  table_roi_id: '77b727c9-1296-4915-9258-64ee45d2c8f6',
                },
                {
                  table_row_index: 0,
                  table_column_index: 5,
                  indicator_text: '2',
                  table_roi_id: '77b727c9-1296-4915-9258-64ee45d2c8f6',
                },
                {
                  table_row_index: 0,
                  table_column_index: 7,
                  indicator_text: '4',
                  table_roi_id: '77b727c9-1296-4915-9258-64ee45d2c8f6',
                },
                {
                  table_row_index: 0,
                  table_column_index: 8,
                  indicator_text: '5',
                  table_roi_id: '77b727c9-1296-4915-9258-64ee45d2c8f6',
                },
                {
                  table_row_index: 0,
                  table_column_index: 10,
                  indicator_text: '7',
                  table_roi_id: '77b727c9-1296-4915-9258-64ee45d2c8f6',
                },
                {
                  table_row_index: 0,
                  table_column_index: 11,
                  indicator_text: '8',
                  table_roi_id: '77b727c9-1296-4915-9258-64ee45d2c8f6',
                },
                {
                  table_row_index: 0,
                  table_column_index: 13,
                  indicator_text: '10',
                  table_roi_id: '77b727c9-1296-4915-9258-64ee45d2c8f6',
                },
                {
                  table_row_index: 0,
                  table_column_index: 14,
                  indicator_text: '11',
                  table_roi_id: '77b727c9-1296-4915-9258-64ee45d2c8f6',
                },
              ],
            },
            {
              visit_timepoint: [],
            },
            {
              epoch_timepoint: [
                {
                  table_row_index: 0,
                  table_column_index: 1,
                  indicator_text: 'Follow-up',
                  table_roi_id: '77b727c9-1296-4915-9258-64ee45d2c8f6',
                },
                {
                  table_row_index: 0,
                  table_column_index: 2,
                  indicator_text: 'Follow-up',
                  table_roi_id: '77b727c9-1296-4915-9258-64ee45d2c8f6',
                },
                {
                  table_row_index: 0,
                  table_column_index: 6,
                  indicator_text: 'Follow-up',
                  table_roi_id: '77b727c9-1296-4915-9258-64ee45d2c8f6',
                },
                {
                  table_row_index: 0,
                  table_column_index: 9,
                  indicator_text: 'Follow-up',
                  table_roi_id: '77b727c9-1296-4915-9258-64ee45d2c8f6',
                },
                {
                  table_row_index: 0,
                  table_column_index: 3,
                  indicator_text: 'Follow-up',
                  table_roi_id: '77b727c9-1296-4915-9258-64ee45d2c8f6',
                },
                {
                  table_row_index: 0,
                  table_column_index: 4,
                  indicator_text: 'Follow-up',
                  table_roi_id: '77b727c9-1296-4915-9258-64ee45d2c8f6',
                },
                {
                  table_row_index: 0,
                  table_column_index: 5,
                  indicator_text: 'Follow-up',
                  table_roi_id: '77b727c9-1296-4915-9258-64ee45d2c8f6',
                },
                {
                  table_row_index: 0,
                  table_column_index: 7,
                  indicator_text: 'Follow-up',
                  table_roi_id: '77b727c9-1296-4915-9258-64ee45d2c8f6',
                },
                {
                  table_row_index: 0,
                  table_column_index: 8,
                  indicator_text: 'Follow-up',
                  table_roi_id: '77b727c9-1296-4915-9258-64ee45d2c8f6',
                },
                {
                  table_row_index: 0,
                  table_column_index: 10,
                  indicator_text: 'Follow-up',
                  table_roi_id: '77b727c9-1296-4915-9258-64ee45d2c8f6',
                },
              ],
            },
            {
              window_timepoint: [],
            },
          ],
          studyProcedure: [
            {
              table_row_index: 0,
              table_column_index: 0,
              indicator_text: 'Study Procedures',
            },
            {
              table_row_index: 13,
              table_column_index: 0,
              indicator_text: 'Adverse events',
            },
            {
              table_row_index: 14,
              table_column_index: 0,
              indicator_text: 'Concomitant  medications',
            },
            {
              table_row_index: 4,
              table_column_index: 0,
              indicator_text: 'Informed consent',
            },
            {
              table_row_index: 5,
              table_column_index: 0,
              indicator_text: 'Demographic history',
            },
            {
              table_row_index: 6,
              table_column_index: 0,
              indicator_text: 'Medical history',
            },
            {
              table_row_index: 7,
              table_column_index: 0,
              indicator_text: 'Liver transplant: specific medical history',
            },
            {
              table_row_index: 8,
              table_column_index: 0,
              indicator_text: 'Physical examination',
            },
            {
              table_row_index: 9,
              table_column_index: 0,
              indicator_text: 'Vital signs',
            },
            {
              table_row_index: 10,
              table_column_index: 0,
              indicator_text: 'Inclusion/exclusion criteria',
            },
            {
              table_row_index: 11,
              table_column_index: 0,
              indicator_text: 'PPD skin test',
            },
            {
              table_row_index: 16,
              table_column_index: 0,
              indicator_text: 'Hematology',
            },
            {
              table_row_index: 17,
              table_column_index: 0,
              indicator_text: 'Comprehensive chemistry',
            },
            {
              table_row_index: 18,
              table_column_index: 0,
              indicator_text: 'Basic chemistry',
            },
            {
              table_row_index: 19,
              table_column_index: 0,
              indicator_text: 'Liver panel',
            },
            {
              table_row_index: 20,
              table_column_index: 0,
              indicator_text: 'Autoantibodies',
            },
            {
              table_row_index: 21,
              table_column_index: 0,
              indicator_text: 'Quantitative immunoglobulins',
            },
            {
              table_row_index: 22,
              table_column_index: 0,
              indicator_text: 'Viral serology3',
            },
            {
              table_row_index: 3,
              table_column_index: 0,
              indicator_text: 'Urine hCG',
            },
            {
              table_row_index: 4,
              table_column_index: 0,
              indicator_text:
                'Glomerular filtration rate (creatinine and height)',
            },
            {
              table_row_index: 5,
              table_column_index: 0,
              indicator_text: 'Hemoglobin A1C',
            },
            {
              table_row_index: 6,
              table_column_index: 0,
              indicator_text: 'Tacrolimus or cyclosporine serum levels',
            },
            {
              table_row_index: 8,
              table_column_index: 0,
              indicator_text:
                'Whole blood  quantitative PCR for CMV reactivation',
            },
            {
              table_row_index: 9,
              table_column_index: 0,
              indicator_text:
                'Whole blood  quantitative PCR for EBV reactivation',
            },
            {
              table_row_index: 11,
              table_column_index: 0,
              indicator_text: 'Liver biopsies4',
            },
            {
              table_row_index: 13,
              table_column_index: 0,
              indicator_text: 'Whole blood flow cytometry panel staining',
            },
            {
              table_row_index: 14,
              table_column_index: 0,
              indicator_text: 'Frozen PBMC T-cell assays 9',
            },
            {
              table_row_index: 15,
              table_column_index: 0,
              indicator_text: 'Liver biopsy histology',
            },
            {
              table_row_index: 16,
              table_column_index: 0,
              indicator_text: 'Whole-blood gene expression profiling',
            },
            {
              table_row_index: 17,
              table_column_index: 0,
              indicator_text: 'Liver biopsy RNA gene expression profiling',
            },
            {
              table_row_index: 18,
              table_column_index: 0,
              indicator_text: 'Serum secreted cytokines',
            },
            {
              table_row_index: 3,
              table_column_index: 0,
              indicator_text: 'Serum HLA alloantibodies',
            },
            {
              table_row_index: 4,
              table_column_index: 0,
              indicator_text: 'Whole blood DNA HLA genotypes9,  9',
            },
          ],
          normalized_SOA: [
            {
              id: '62f68f3b-34b5-44d4-a1ca-3d8aa66ee2d8',
              epoch_timepoint: 'Follow-up',
              ProcessVersion: '15.15.8.0',
              table_sequence_index: -1,
              doc_id: 'd4153421-2b47-4ec5-b21c-80d907d73227',
              indicator_text: 'X',
              roi_id: 'f722444d-3c4e-4867-9361-641b1de81a93',
              study_cohort: '',
              run_id: '',
              month_timepoint: '',
              table_row_index: 14,
              visit_timepoint: '',
              assessment: 'Concomitant  medications',
              pname: 'NCT00320606.pdf',
              table_column_index: 4,
              week_timepoint: '',
              assessment_text: 'Concomitant  medications',
              procedure: '',
              section: '',
              window_timepoint: '',
              cycle_timepoint: '1',
              procedure_text: '',
              table_link_text:
                'List of Appendices Appendix 1.  Schedule of Events:  Gradual to Complete Withdrawal Plus 3 Months of High-intensity Follow-up',
              year_timepoint: '',
              day_timepoint: '',
              ProcessMachineName: 'CA2SPDML03Q',
              DocumentSequenceIndex: -1,
              dts: '20230303044213',
              table_roi_id: '77b727c9-1296-4915-9258-64ee45d2c8f6',
              footnotes: [
                '2 Additional biopsies will be performed if necessary to rule out rejection.',
                '2 Additional biopsies will be performed if necessary to rule out rejection.',
                '1 Can be performed within 9 weeks before the liver biopsy visit.',
                '1 Can be performed within 9 weeks before the liver biopsy visit.',
                '2 LFTs must be performed upon diagnosis of allograft dysfunction or rejection and at the resolution of rejection (see sections 5.5.2 and 5.5.3.1).  Additional LFTs may be performed during rejection at the investigators discretion.',
                '4 Additional biopsies will be done to rule out rejection if necessary.',
                '4 Additional biopsies will be done to rule out rejection if necessary.',
                '5 Will be performed within 4 to 8 weeks after the last dose of immunosuppressant is taken.',
                '6 Will be performed only at visit 12 and not at visit 24.',
                '8 Please try to collect blood at assigned visit -2; if this is not possible,  collect at visit 1.  If not able to collect at visit 1,  please collect at visit 0.',
                '9 To be collected from living donor and nondonor parents after they have signed the informed consent; blood',
                '8 Please try to collect blood at assigned visit -2; if this is not possible,  collect at visit 1.  If not able to collect at visit 1,  please collect at visit 0.',
                '9 To be collected from living donor and nondonor parents after they have signed the informed consent; blood',
                '9 To be collected from living donor and nondonor parents after they have signed the informed consent; blood',
                '9 To be collected from living donor and nondonor parents after they have signed the informed consent; blood',
                '9 To be collected from living donor and nondonor parents after they have signed the informed consent; blood',
                '5 Will be performed within 4 to 8 weeks after the last dose of immunosuppressant is taken.',
                '6 Will be performed only at visit 12 and not at visit 24.',
                '8 Please try to collect blood at assigned visit -2; if this is not possible,  collect at visit 1.  If not able to collect at visit 1,  please collect at visit 0.',
                '5 Will be performed within 4 to 8 weeks after the last dose of immunosuppressant is taken.',
                '6 Will be performed only at visit 12 and not at visit 24.',
                '8 Please try to collect blood at assigned visit -2; if this is not possible,  collect at visit 1.  If not able to collect at visit 1,  please collect at visit 0.',
                '8 Please try to collect blood at assigned visit -2; if this is not possible,  collect at visit 1.  If not able to collect at visit 1,  please collect at visit 0.',
                '9 To be collected from living donor and nondonor parents after they have signed the informed consent; blood',
                '8 Please try to collect blood at assigned visit -2; if this is not possible,  collect at visit 1.  If not able to collect at visit 1,  please collect at visit 0.',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Liver biopsy will be performed as part of the E36 visit. Additional biopsies will be performed according to protocol guidelines or at the discretion of the site investigator.{0,0,0,0}',
                '2 Will be performed only at visit M1 and not at visit M13.',
                '2 Will be performed only at visit M1 and not at visit M13.',
                '2 Will be performed only at visit M1 and not at visit M13.',
                '2 Will be performed only at visit M1 and not at visit M13.',
                '2 Will be performed only at visit M1 and not at visit M13.',
                '3 Do not collect if last sample was collected less than 6 weeks before visit M1.',
                '2 Will be performed only at visit M1 and not at visit M13.',
                '2 Will be performed only at visit M1 and not at visit M13.',
                '4 Additional biopsies will be performed if necessary to rule out rejection.',
                '4 Additional biopsies will be performed if necessary to rule out rejection.',
              ],
              marked_record: {
                'Concomitant  medications': ['Follow-up', '1'],
              },
            },
            {
              id: '706d09c5-780f-414b-a36a-d3ed97dc1121',
              epoch_timepoint: 'Follow-up',
              ProcessVersion: '15.15.8.0',
              table_sequence_index: -1,
              doc_id: 'd4153421-2b47-4ec5-b21c-80d907d73227',
              indicator_text: 'X',
              roi_id: 'f722444d-3c4e-4867-9361-641b1de81a93',
              study_cohort: '',
              run_id: '',
              month_timepoint: '',
              table_row_index: 14,
              visit_timepoint: '',
              assessment: 'Concomitant  medications',
              pname: 'NCT00320606.pdf',
              table_column_index: 5,
              week_timepoint: '',
              assessment_text: 'Concomitant  medications',
              procedure: '',
              section: '',
              window_timepoint: '',
              cycle_timepoint: '2',
              procedure_text: '',
              table_link_text:
                'List of Appendices Appendix 1.  Schedule of Events:  Gradual to Complete Withdrawal Plus 3 Months of High-intensity Follow-up',
              year_timepoint: '',
              day_timepoint: '',
              ProcessMachineName: 'CA2SPDML03Q',
              DocumentSequenceIndex: -1,
              dts: '20230303044213',
              table_roi_id: '77b727c9-1296-4915-9258-64ee45d2c8f6',
              footnotes: [
                '2 Additional biopsies will be performed if necessary to rule out rejection.',
                '2 Additional biopsies will be performed if necessary to rule out rejection.',
                '1 Can be performed within 9 weeks before the liver biopsy visit.',
                '1 Can be performed within 9 weeks before the liver biopsy visit.',
                '2 LFTs must be performed upon diagnosis of allograft dysfunction or rejection and at the resolution of rejection (see sections 5.5.2 and 5.5.3.1).  Additional LFTs may be performed during rejection at the investigators discretion.',
                '4 Additional biopsies will be done to rule out rejection if necessary.',
                '4 Additional biopsies will be done to rule out rejection if necessary.',
                '5 Will be performed within 4 to 8 weeks after the last dose of immunosuppressant is taken.',
                '6 Will be performed only at visit 12 and not at visit 24.',
                '8 Please try to collect blood at assigned visit -2; if this is not possible,  collect at visit 1.  If not able to collect at visit 1,  please collect at visit 0.',
                '9 To be collected from living donor and nondonor parents after they have signed the informed consent; blood',
                '8 Please try to collect blood at assigned visit -2; if this is not possible,  collect at visit 1.  If not able to collect at visit 1,  please collect at visit 0.',
                '9 To be collected from living donor and nondonor parents after they have signed the informed consent; blood',
                '9 To be collected from living donor and nondonor parents after they have signed the informed consent; blood',
                '9 To be collected from living donor and nondonor parents after they have signed the informed consent; blood',
                '9 To be collected from living donor and nondonor parents after they have signed the informed consent; blood',
                '5 Will be performed within 4 to 8 weeks after the last dose of immunosuppressant is taken.',
                '6 Will be performed only at visit 12 and not at visit 24.',
                '8 Please try to collect blood at assigned visit -2; if this is not possible,  collect at visit 1.  If not able to collect at visit 1,  please collect at visit 0.',
                '5 Will be performed within 4 to 8 weeks after the last dose of immunosuppressant is taken.',
                '6 Will be performed only at visit 12 and not at visit 24.',
                '8 Please try to collect blood at assigned visit -2; if this is not possible,  collect at visit 1.  If not able to collect at visit 1,  please collect at visit 0.',
                '8 Please try to collect blood at assigned visit -2; if this is not possible,  collect at visit 1.  If not able to collect at visit 1,  please collect at visit 0.',
                '9 To be collected from living donor and nondonor parents after they have signed the informed consent; blood',
                '8 Please try to collect blood at assigned visit -2; if this is not possible,  collect at visit 1.  If not able to collect at visit 1,  please collect at visit 0.',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Participants enter extended follow-up after completing low-intensity follow-up.{0,0,0,0}',
                'Liver biopsy will be performed as part of the E36 visit. Additional biopsies will be performed according to protocol guidelines or at the discretion of the site investigator.{0,0,0,0}',
                '2 Will be performed only at visit M1 and not at visit M13.',
                '2 Will be performed only at visit M1 and not at visit M13.',
                '2 Will be performed only at visit M1 and not at visit M13.',
                '2 Will be performed only at visit M1 and not at visit M13.',
                '2 Will be performed only at visit M1 and not at visit M13.',
                '3 Do not collect if last sample was collected less than 6 weeks before visit M1.',
                '2 Will be performed only at visit M1 and not at visit M13.',
                '2 Will be performed only at visit M1 and not at visit M13.',
                '4 Additional biopsies will be performed if necessary to rule out rejection.',
                '4 Additional biopsies will be performed if necessary to rule out rejection.',
              ],
              marked_record: {
                'Concomitant  medications': ['Follow-up', '2'],
              },
            },
          ],
        },
      ],
    },
  },
};
export default initialState;
